sstsimulator/sst-core

- simulation.cc
- simulation.h
- syncManager.cc
- threadSyncSimpleSkip.cc
- threadSyncSimpleSkip.h
Made Simulation::endSimulation() a node level collective call to fix deadlock on exit.  Removed extraneous barriers in sync objects.
> Fix deadlock on exit

- statapi/stathistogram.h
This is the fix for the issue I just posted.
> Prevent histogram bin labels from overflowing if larger than 32 bits

- stopAction.h
StopAction should not use cout (in fact, nothing should), as threading with cout is insane at best.
Should help address sst-elements/issue78
> [threading] Don't use cout - not thread-intelligent

- statapi/statengine.cc
- statapi/statengine.h
Can be called by a component to output statistics for all components and subcomponents in the simulation
> StatAPI: Add performGlobalStatisticOutput function

- config.cc
- config.h
- main.cc
Need to support better timing when verbose is not enabled. Currently with verbose large simulations dump a lot of extra info to stdout. This option prints only timing.
> Adds an option to SST to print timing even when verbose is not enabled

- interfaces/simpleMem.h
Since SubComponent inherits from Module, all current code should
still work.  Will later change classes that inherit from SimpleMem
to use the capabilities of SubComponent.
> Made simpleMem inherit from SubComponent instead of Module.

- cfgoutput/jsonConfigOutput.cc
- cfgoutput/pythonConfigOutput.cc
- cfgoutput/xmlConfigOutput.cc
- main.cc
- params.h
- statapi/componentregisterstat_impl.h
- statapi/stathistogram.h
- statapi/statoutputconsole.cc
- statapi/statoutputcsv.cc
- statapi/statoutputcsvgz.cc
- statapi/statoutputtxt.cc
- statapi/statoutputtxtgz.cc
Removed find, and operator[] from Params.  Also got rid of most of
the typedefs that were mimicking the map interface.  Also marked
all the find_* functions are deprecated.  Now users should use the
templated find<T> and find_array<T> functions.
> Removed last pieces of map-like interface from Params.

- objectComms.h
Fixes a compiler warning with regards to mismatched `delete` and `delete []`
> Fix a warning about mismatched delete calls

- config/sst_enable_core_profile.m4
- config/sst_enable_debug_output.m4
- config/sst_enable_event_tracking.m4
- configure.ac
Restores:
- Core Debug Preprocessor Options (for `Output` class)
- Core Profiling
- Core Event Tracking
> Restores Core Configuration Options Removed during External-Core-ization

- src/sst/core/config.h
`--add-lib-path` support was accidentally dropped recently.  This patch restores it.
> Re-enable the --add-lib-path support

- src/sst/core/model/pymodel.cc
Address Issue #63. Adds 'getThreadCount()' as an SST python method.
> [pymodel] Add  getThreadCount() method to SST Python

- src/sst/core/Makefile.am
- src/sst/core/params.h
- src/sst/core/serialization/serialize.h
- src/sst/core/serialization/serialize_deque.h
- src/sst/core/serialization/serialize_serializable.h
- src/sst/core/unitAlgebra.h
Added some extra checking into the serialization.  Old code would attempt to just treat any unknown object as a primitive and do a copy of size sizeof(T).  New code will fail at compile time if it doesn't know about how to serialize an object.  Also add new serialization to Params and added serialization for std::deque.
> Serialization

- src/sst/core/serialization/serializable.h
- src/sst/core/serialization/serialize.h
- src/sst/core/serialization/serialize_array.h
- src/sst/core/serialization/serialize_serializable.h
The following changes were made:
- serializing a std::pair will now serialize each part
independently.
- Can now serialize pointers to values satisfying
is_fundamental || is_enum.  Could already serialize
pointers to serializable, but this is now a
separate expansion.
- Serialization of statically sized arrays will now work
for anything that is serializable (used to only work
for base types).
> Added more serialization functionality.

- src/sst/core/component.h
- src/sst/core/main.cc
- src/sst/core/simulation.cc
Move the shutdown at end of simulation::finish() instead of at end of
simulation::run().  Also cleaned up statistic’s debris code in
component.h
> Change Statistics shutdown per issue #61

- src/sst/core/main.cc
Don't want/need extra #include of MPI, especially when MPI is disabled.
> Remove extra (unguarded) #include of mpi.h

- src/sst/core/componentInfo.cc
- src/sst/core/componentInfo.h
- src/sst/core/simulation.cc
Attempt to fix #126.  Delete components when Simulation is destroyed.  (Thus, calling destructors of components.)
> Call component destructors when owning simulation is destroyed

- config/sst_check_zoltan.m4
Requested by @allevin. Fixes issue with Zoltan configure where `--with-zoltan=` supplied but value is empty string. This previously would configure but without Zoltan enabled. This should in-fact error. Change set now errors and prints appropriate message.
> Fix issue with Zoltan configure where --with-zoltan supplied by is empty string

- src/sst/core/configGraph.cc
Fixed typo in *src/sst/core/configGraph.cc*, I assumed that "nane" should be "name" instead.
> fix typo in configGraph.cc

- src/sst/core/config.cc
There are 2 "output-directory" options in *config.cc* file (line 147 and line 151), which would result an error when running something like *sst foo.py --output-directory bar/*
> Error: option '--output-directory' is ambiguous and matches different versions of '--output-directory'
Removing one of them would eliminate this error.
Also fixed some indentation along the way...
> Remove redundant "--output-directory" in config.cc

- src/sst/core/sstinfo.cc
sst-info was printing out the previous directory tested, rather than the current directory tested, when such directory could not be found.
> Fix printing incorrect directory when a directory cannot be opened

- src/sst/core/env/envconfig.cc
- src/sst/core/env/envquery.cc
Add SST Configuration File Locking when Reading/Registering (`sst-register` and `sst` now use exclusive and shared file locks respectively to prevent simultaneous updating while other operations are in flight). These are blocking lock calls to ensure operations are queued up on the configuration files to execute cleanly.
> Add SST Configuration File Locking when Reading/Registering

- src/sst/core/stringize.h
In efforts to remove / limit BOOST dependencies, re-implement a few string-based utilities, such as tokenizers.  This commit is necessary before the sst-elements/bjmoor/boostCleanup branch can be merged into sst-elements/devel.
> [stringize] Added functions to replace equivalent boost string functions

- src/sst/core/stringize.h
Should call correct strcasecmp.
> [stringize] do not recurse, call the standard library of strcasecmp

- src/sst/core/stringize.h
`operator()` should return void, not declare as bool.
Should fix #168
> Address #168

- src/sst/core/interfaces/simpleMem.h
For memory accesses that have a src and dst or multiple src/dst
Also removed the unused groupId which was used for statistics
> Added ability to specify multiple addresses in the simpleMem interface

- src/sst/core/config.cc
SST was crashing when bad options were passed on the commandline.   Was missing a 'null-row' in the LongOpts.
> [fix] do not crash when bad options are passed

- configure.ac
- src/sst/core/config.cc
Update version data in sst-elements to indicate that the version is coming from github not from a release.  This is related to sst-core issue#177.
> update version data in configure.ac and display of sst --version

- src/sst/core/cfgoutput/dotConfigOutput.cc
- src/sst/core/main.cc
Tweak `main()` to only do the Graph Config outputs (for example json, dot, etc) only on a single MPI rank, to avoid overwrites.
Tweak the Dot graph config output to designate Threads as subgraphs (in addition to Ranks), and to add latency to edge labels.
> Graph Output tweaks

- src/sst/core/main.cc
- src/sst/core/rankSyncParallelSkip.cc
- src/sst/core/rankSyncParallelSkip.h
- src/sst/core/rankSyncSerialSkip.cc
- src/sst/core/rankSyncSerialSkip.h
- src/sst/core/simulation.cc
- src/sst/core/simulation.h
- src/sst/core/syncManager.cc
- src/sst/core/syncManager.h
- src/sst/core/threadSyncSimpleSkip.cc
- src/sst/core/threadSyncSimpleSkip.h
- src/sst/core/threadsafe.h
A couple of things in here:
- Break apart uses of Barrier objects so fewer barriers are re-used across different locations
- Remove some blocks of commented-out code
- Add / move some barriers to fix at least one race-condition that would lead to deadlock.
> Thread syncronization fixes

- src/sst/core/simulation.cc
- src/sst/core/simulation.h
- src/sst/core/syncManager.cc
- src/sst/core/syncManager.h
Address #207 by removing old (unused) `sync` variable from Simulation.  Rather, gather that information from `SyncManager`
> Remove unused sync from Simulation.  Fixes #207

- src/sst/core/threadSyncSimpleSkip.cc
Fix a warning from GCC that braces were not where they should be.
> Only thread 0 should resize the barriers

- src/sst/core/baseComponent.h
- src/sst/core/cfgoutput/pythonConfigOutput.cc
- src/sst/core/cfgoutput/pythonConfigOutput.h
- src/sst/core/componentInfo.cc
- src/sst/core/componentInfo.h
- src/sst/core/configGraph.cc
- src/sst/core/configGraph.h
- src/sst/core/model/pymodel_comp.cc
- src/sst/core/statapi/statoutputhdf5.cc
Allow Python API to specify coordinates for Components.  HDF5 StatOutput will record these.
> Add coordinates to Python API

- src/sst/core/Makefile.am
- src/sst/core/interprocess/circularBuffer.h
- src/sst/core/interprocess/sstmutex.h
Need to remove direct calls to pthread functions for PIN. This swaps out the pthread calls for C++11 threading based classes.
> Switch circularBuffer over to use C++11

- src/sst/core/interprocess/sstmutex.h
Change custom mutex (`SSTMutex`) over to use assembly directly. Cannot call `_mm_*` functions if we want to use PIN-3.2 because these are not compatible with PIN's customized system header files.
> Update custom mutex class so it directly calls PAUSE assembly

- src/sst/core/sharedRegion.cc
- src/sst/core/statapi/statgroup.cc
- src/sst/core/statapi/statoutputhdf5.cc
- src/sst/core/warnmacros.h
GCC 4.x does not understand `-Wsuggest-override`.  Don't bother putting that in.
Adding includes that appear to be needed.  Not sure why they're showing up now, and not before.
> Add some missing includes, and squelch warning on GCC 4

- config/sst_check_python.m4
- src/sst/core/Makefile.am
Additional library checking for Python when used in SST. This helps to address #187 (which is really a Python issue).
> Additional Library Checking for Python

- src/sst/core/elementinfo.h
Addresses #246
Allow external elements to be built, without requiring them to use the SST namespace.
> Add 'SST::' namespace prefixes to macros

- src/sst/core/elementinfo.h
- src/sst/core/elibase.h
- src/sst/core/factory.cc
- src/sst/core/factory.h
Old ELI will now build new ELI data structures, so calls to old ELI data structures have been removed.  Documentation macros for params, ports, stats and subcomponent slots are now optional when there is nothing to document.  Preparing to remove the separate SST_ELI_DOCUMENENT_VERSION macro.  The version will now be part of the register calls.  This pull request temporarily disables element descriptions for all elements, category for components and interface for subcomponents and modules.  This will be added back in with the next pull request, but elements needs to be updated first.
> Changes to new ELI

- src/sst/core/element.h
Found via customer:   Core header files should not `#include <foo.h>`, when `foo.h` is part of the core.  Supply the correct path.
> element.h should include correct path to elibase.h

- src/sst/core/config.cc
- src/sst/core/config.h
Can put output files into a specific directory. Useful when running large numbers of experiments. See Issue: #145.
> Add Support for Directory Output in SST

- src/sst/sst.conf
We need to be able to detect if the core is built with MPI so we can build support libraries for elements later. This should not be used to built elements. We do however build some libraries for our elements that may require MPI when they interact with applications etc.
> Add MPI to SST Configuration Saving

- configure.ac
- src/sst/core/env/envquery.cc
Reported in bug #270 and #182 if `--prefix` is not set for configuration then `sst-config` is unable to find any root for configuration information and errors. This detects the "NONE" setting (auto-configuration records the parameter is unset) and overrides this to `/usr/local`. Tested on Mac OS X.
> Fixes #270 where Configuration Prefix is set to NONE and Configuration Cannot be Read

- src/sst/core/statapi/statoutputjson.cc
Fixes unused parameter warnings when compiling the new JSON statistics output class. Core should compile clean with picky warnings turned on.
> Fix Warning when Compiling JSON Statistics Output

- src/sst/core/sstinfo.cc
- src/sst/core/sstinfo.h
Tweaks to SSTINFO to support ACS's SST templating GUI.   Specifically, make the XML valid, and able to print to `stdout`.
> sstinfo tweaks

- src/sst/core/config.cc
- src/sst/core/sstinfo.cc
The calls to getopt_long currently assume return type will be `char`. The return type is actually `int` and GCC 4.8.5 on POWER8 complains that the check to `-1` will always be false, causing the compiler to generate code in which SST will not run. This fixes the behavior on POWER8 w/ GCC 4.8.5. This is also a problem on `sst-info`.
> Fix Runtime Error when using getopt_long

- src/sst/core/sstinfo.cc
Subcomponents have documented ports.  `sstinfo` should report them.
> [sstinfo] SubComponents document their ports

- src/sst/core/configGraph.cc
- src/sst/core/configGraph.h
Enable top-level python statistic enablement functions to work on SubComponents.
* `sst.enableAllStatisticsForAllComponents()`
* `sst.enableAllStatisticsForComponentType()`
* `sst.enableStatisitcForAllComponents()`
* `sst.enableStatisticForComponentType()`
> Top-level stat-enablements should work on subComponents

- src/sst/core/params.h
adding better error handling to find_array in params module; now checks to ensure that the incoming strings are enclosed by brackets; reports error otherwise and throws exception.  
This is a fix for Issue #308
> adding better error handling to find_array in params module

- src/sst/core/sharedRegion.cc
- src/sst/core/syncManager.cc
SharedRegions need to be updated between every cycle of init(), so that the data can be used during init().  One use case is building up a logical to physical mapping which is needed during init() to route init events.
> Shared region fix

- src/sst/core/timeLord.cc
TimeConverters that are created from an exact 0 are allowed, but TimeConverters that become zero because their time interval is smaller than the atomic timebase in the core will abort with an error.
This addresses issue #292.
> Added check for TimeConverters with time intervals that are too small.

- src/sst/core/model/element_python.cc
Added check in SSTElementPythonModule::load() to make sure the primary module was specified.
Addresses issue #278.
> Python Module check

- src/sst/core/interfaces/simpleMem.h
Adding CustomCmd SimpleMem Event type for dispatching and handling arbitrarily custom memory requests for any potential CPU driver.  Support for all Miranda SST-Elements drivers is forthcoming in a patch from sst-elements:mh_customcmd branch
> Adding CustomCmd SimpleMem Request Structure

- src/sst/core/baseComponent.h
- src/sst/core/componentInfo.cc
- src/sst/core/componentInfo.h
- src/sst/core/interfaces/simpleNetwork.h
- src/sst/core/link.cc
- src/sst/core/link.h
- src/sst/core/main.cc
- src/sst/core/rankSyncParallelSkip.cc
- src/sst/core/rankSyncParallelSkip.h
- src/sst/core/rankSyncSerialSkip.cc
- src/sst/core/rankSyncSerialSkip.h
- src/sst/core/simulation.cc
- src/sst/core/simulation.h
- src/sst/core/syncBase.cc
- src/sst/core/syncBase.h
- src/sst/core/syncManager.cc
- src/sst/core/syncManager.h
- src/sst/core/threadSync.cc
- src/sst/core/threadSync.h
- src/sst/core/threadSyncSimpleSkip.cc
- src/sst/core/threadSyncSimpleSkip.h
As part of this, added calls sendUntimedData and recvUntimed data.
There will eventually replace the send/recvInitData calls to keep
the names more generic.  As part of this, changed all variables with
init in the name to use untimed instead (except for those which were
referring specifically to the init() stage.
> Added an iterative complete() stage following the run() stage.

- src/sst/core/configGraph.cc
- src/sst/core/configGraph.h
- src/sst/core/model/pymodel.h
- src/sst/core/model/pymodel_link.cc
- src/sst/core/part/Makefile.inc
- src/sst/core/part/selfpart.cc
- src/sst/core/part/selfpart.h
Fixes the issue of "self" partitioner not being found. Fixed an issue where calling setNoCut() after calling connect() in the python would not properly set the no-cut attribute in the config graph.
> Partition fixes

- src/sst/core/bootshared.cc
Initializes arrays so that Valgrind no longer complains about arrays being uninitialized.
> Fixes a Valgrind warning during the SST boot engine

- src/sst/core/Makefile.am
Removing sst-config.h from src/sst/core/Makefile.am  to prevent file from being added to distribution when running `make dist`.  
The sst_config.h is generated dynamically by the configure script, When it was in the Makefile.am, it was being distributed causing issues with out of source builds.
This change removes it from the distribution.
See issue #302.
> Remove sst_config.h from Makefile.am

- src/sst/core/part/rrobin.cc
This is the only partitioner with unconditional output, so using roundrobin breaks all my scripts.
> Remove output from roundrobin partitioner

- src/sst/core/output.cc
This causes the errors to get intermingled with normal output, which breaks scriptability.
> Print errors from Output to stderr instead of stdout

- src/sst/core/Makefile.am
- src/sst/core/config.cc
- src/sst/core/config.h
- src/sst/core/factory.cc
- src/sst/core/impl/Makefile.inc
- src/sst/core/impl/timevortex/Makefile.inc
- src/sst/core/impl/timevortex/timeVortexPQ.cc
- src/sst/core/impl/timevortex/timeVortexPQ.h
- src/sst/core/simulation.cc
- src/sst/core/timeVortex.h
TimeVortex is now a module which can be loaded.  The default is
sst.timevortex.priority_queue and is the same implementation
that has been used to this point.
> Added ability to specify the implemention of TimeVortex to be used.

- src/sst/core/Makefile.am
- src/sst/core/impl/Makefile.inc
- src/sst/core/impl/partitioners/Makefile.inc
- src/sst/core/impl/partitioners/linpart.cc
- src/sst/core/impl/partitioners/linpart.h
- src/sst/core/impl/partitioners/rrobin.cc
- src/sst/core/impl/partitioners/rrobin.h
- src/sst/core/impl/partitioners/selfpart.cc
- src/sst/core/impl/partitioners/selfpart.h
- src/sst/core/impl/partitioners/simplepart.cc
- src/sst/core/impl/partitioners/simplepart.h
- src/sst/core/impl/partitioners/singlepart.cc
- src/sst/core/impl/partitioners/singlepart.h
- src/sst/core/impl/partitioners/zoltpart.cc
- src/sst/core/impl/partitioners/zoltpart.h
- src/sst/core/part/Makefile.inc
- src/sst/core/sstpart.h
Partitioners are now in the core/impl directory to denote that the
implementations are not part of the public API, though they can still
be accessed through the module interface.
The file sst/core/part/sstpart.h has been deprecated and will be
removed in SST 9.0.  The file has been moved to sst/core/sstpart.h.
> Moved partitioners from sst/core/part to sst/core/impl/partitioners.

- src/sst/core/baseComponent.cc
- src/sst/core/component.cc
In the case where a named SubComponent loaded an unnamed SubComponent,
the unnamed SubComponent was seeing the link map from the parent
Component instead of from the named SubComponent.  Now, it will see
the link map from the closest named SubComponent in the load tree.
> Fixed an issue with interaction between named and unnamed SubComponents.

- src/sst/core/output.h
Can improve simulation performance by up to 20% (@mjleven).
> Add debugPrefix call for Output objects.

- src/sst/core/elementinfo.h
For functions that return by value, the const is unnecessary and causes
a compiler warning when the function is used.
> Fix compiler warnings about discarded qualifiers

- src/sst/core/bootsst.cc
- src/sst/core/config.cc
- src/sst/core/config.h
Returns options to print SST configuration for in-field debugging.
Options include: `sst --print-env` or `SST_DISPLAY_ENV=1` and `SST_PRINT_ENV=1` (consistent with our previous ways to print environment configuration).
> Adds SST Configuration Printing

- src/sst/core/elibase.h
Required to get SST to compile with GCC 8.0.
> Fix missing functional Header to get SST to compile with GCC 8.0

- src/sst/core/model/element_python.h
This needs to go in before macro can completely get rid of old ELI.... which needs to happen before the subcomponent refactor can go in.
> Python load 395

- src/sst/core/eli/elementinfo.h
GCC 4.8.2 apparently fails doing template argument deduction for variadic templates. 
This removes the need for variadic templates in a couple places, getting 4.8.2 to work (hopefully)
> GCC 4.8.2 workaround

- src/sst/core/Makefile.am
- src/sst/core/activity.h
- src/sst/core/baseComponent.cc
- src/sst/core/baseComponent.h
- src/sst/core/component.cc
- src/sst/core/component.h
- src/sst/core/componentExtension.h
- src/sst/core/componentInfo.cc
- src/sst/core/componentInfo.h
- src/sst/core/configGraph.cc
- src/sst/core/configGraph.h
- src/sst/core/eli/elementbuilder.h
- src/sst/core/eli/elementinfo.h
- src/sst/core/eli/elibase.h
- src/sst/core/factory.cc
- src/sst/core/factory.h
- src/sst/core/interfaces/simpleMem.h
- src/sst/core/interfaces/simpleNetwork.h
- src/sst/core/link.cc
- src/sst/core/link.h
- src/sst/core/linkMap.h
- src/sst/core/output.cc
- src/sst/core/output.h
- src/sst/core/simulation.cc
- src/sst/core/sst_types.h
- src/sst/core/statapi/statengine.cc
- src/sst/core/subcomponent.cc
- src/sst/core/subcomponent.h
Update to the SubComponent API.
- Introduces loadUserSubComponent and loadAnonymousSubComponent and deprecates loadSubComponent and loadNamedSubComponent.
- The ELI now requires you to register SubComponent APIs using SST_ELI_REGISTER_SUBCOMPONENT_ELI.
> Subcomp api update

- config/sst_check_python.m4
Adds a check in the `configure` for `python2-config`.
> Add python2-config Check for RHEL8

- src/sst/core/Makefile.am
- src/sst/core/baseComponent.cc
- src/sst/core/baseComponent.h
- src/sst/core/componentExtension.cc
- src/sst/core/componentExtension.h
- src/sst/core/eli/categoryInfo.h
- src/sst/core/eli/interfaceInfo.h
- src/sst/core/factory.h
- src/sst/core/interfaces/simpleNetwork.h
- src/sst/core/subcomponent.cc
Disambiguated some of the templated APIs for SubComponent loading and added backward compatibility into the new load*SubComponent calls.  The calls will now try to load using the new API, but will fallback to the old, if needed.  Also added a new call to check if it loaded with the new or old API.
> Subcomp update

- src/sst/core/warnmacros.h
This is needed in the case where use of deprecated APIS is
required to maintain backward compatibility until the next
major release.
> Added ability to suppress warnings about deprecated functions.

- src/sst/core/baseComponent.cc
- src/sst/core/baseComponent.h
- src/sst/core/componentInfo.h
- src/sst/core/module.h
Fixed a bug in SubComponent deletion that would occasionally cause segfaults.
Added the ability to define Module APIs and load them through a new templated function that allows passing parameters to the constructor.
> Module APIs and SubComponent Fix

- src/sst/core/interprocess/ipctunnel.h
Reorder variables in IPCTunnel class to remove compiler warning around initialization order.
```
sst/sst-core/include/sst/core/interprocess/ipctunnel.h: In instantiation of 'SST::Core::Interprocess::IPCTunnel<ShareDataType, MsgType>::IPCTunnel(uint32_t, size_t, size_t, uint32_t) [with ShareDataType = SST::ArielComponent::ArielSharedData; MsgType = SST::ArielComponent::ArielCommand; uint32_t = unsigned int; size_t = long unsigned int]':
./../ariel/ariel_shmem.h:188:104:   required from here
sst/sst-core/include/sst/core/interprocess/ipctunnel.h:265:11: warning: 'SST::Core::Interprocess::IPCTunnel<SST::ArielComponent::ArielSharedData, SST::ArielComponent::ArielCommand>::shmPtr' will be initialized after [-Wreorder]
void *shmPtr;
^
sst/sst-core/include/sst/core/interprocess/ipctunnel.h:263:9: …
```
> Reorder vars to get rid of compiler warnings

- src/sst/core/sstinfo.cc
When generating an XML file with sst-info (e.g. `sst-info -xn`), all `BaseType`s where tagged as "Component" instead of the appropriate tag (Module, SubComponent).
This solution creates the tag calling `BaseType::ELI_baseName()`.
> Fixes issue where sst-info XML output had the wrong format

- src/sst/core/eli/elementinfo.cc
- src/sst/core/sstinfo.cc
Fix stat numbering in sst-info
Use the 'quiet' option to print summary (component names) only
> sstinfo fixes

- src/sst/core/elemLoader.cc
- src/sst/core/elemLoader.h
- src/sst/core/factory.cc
- src/sst/core/factory.h
- src/sst/core/model/pymodel.cc
- src/sst/core/output.cc
- src/sst/core/sstinfo.cc
When components or modules fail to load due to some filesystem or linker reason, we do not print useful error messages currently.  We just print "load failed" and do not print the error messages from `dlopen`.  We do this because the dlopen routines can fail multiple times before succeeding and we don't want a bunch of verbose errors if we don't actually fail.
This change instead collects all error messages in an `ostream`. If the load eventually succeeds, we do not print error messages. In the event of a fatal error, however, all of the `ostream` output is printed to give useful debugging information.
We could potentially make this more fine-grained with a command-line option. I believe what is implemented should be our default behavior.
> Print useful debugging error messages on load failure: Issue #138

- configure.ac
The \s character class does not work in all versions of sed (even
with -E). Use [:space:] instead.
> Fix SST_EXPORT_CFLAGS and SST_EXPORT_CXXFLAGS regex

- src/sst/core/Makefile.am
- src/sst/core/eli/README.md
- src/sst/core/eli/elementbuilder.h
Derived subcomponent APIs should not be required to implement the base Subcomponent constructor if they are only ever used with the derived API.
> don't require unused subcomp ctors: Issue #449

- src/sst/core/statapi/statoutputhdf5.cc
- src/sst/core/statapi/statoutputhdf5.h
Moved a function to cc file to get rid of #include ordering dependencies.
> statoutputhdf5 fix

- src/sst/core/baseComponent.cc
- src/sst/core/baseComponent.h
- src/sst/core/componentInfo.h
- src/sst/core/interfaces/simpleNetwork.h
Needed to put in more #ifndef guards for SimpleNetwork for preview builds.
Added two versions of fatal calls to BaseComponent as a convenience for reported errors and terminating.  The only difference is one takes a bool condition variable to act somewhat like an assert (couldn't use assert as the name since assert is a macro).
> Preview clean up

- src/sst/core/eli/elementinfo.h
Without these changes, we get a slew of warnings
````
'constexpr' non-static member function will not be implicitly 'const' in C++14; add
'const' to avoid a change in behavior [-Wconstexpr-not-const]
constexpr unsigned getMajor() { return major; }
````
> remove constexpr const warnings

- config/sst_check_python.m4
- configure.ac
Rejects Python < 2.6 or between 3.0 & 3.4
> Add correct checks for Python version

- src/sst/core/env/envconfig.cc
Add a newline before each section when registering data into sstsimulator.conf configuration file.  This makes reading the .conf file a bit easier to the puny human.
> Add a newline before each section when registering data into sstsimulator.conf

- configure.ac
- src/sst/core/config.h
This fix is for issue #407, the problem only occurs if both --enable-event-tracking is on and --disable-mem-pools are set.  
In config.h, event_dump_file is only defined if USE_MEMPOOLS is defined (which it is normally).  However, in config.cc if __SST_DEBUG_EVENT_TRACKING__ is defined, then it uses event_dump_file.  
The problem only occurs if both __SST_DEBUG_EVENT_TRACKING__ is defined and USE_MEMPOOLS is not defined -->  --enable-event-tracking is on and --disable-mem-pools configuration settings.
The change is done in configure.ac and checks for either if event tracking is turned on AND mem-pools are turned off, it will then fail the configure with an appropriate error message.
> Fix for issue #407

- src/sst/core/clock.cc
Fix for unused variables warning in OSX Clang.
> Fix for unused variables warning

- src/sst/core/model/xmlToPython.py
Converting xml2Python.py file to make it Python3 compliant.  
The only known use of this file is an existing scheduler test.
Eventually in SST-11, we will remove support for xml2Python.py file.
> Fix xml2Python.py file to work on Py3

- src/sst/core/model/python2/pymodel.cc
- src/sst/core/model/python2/pymodel_comp.cc
- src/sst/core/model/python3/pymodel.cc
- src/sst/core/model/python3/pymodel_comp.cc
- src/sst/core/model/python3/pymodel_statgroup.cc
Apparently python3 passes unicode through to the cpython.  These move all PyByte calls to PyUnicode for python3.  Also fixed a potential memory corruption problem in both python 2 and 3.
> Python3 updates

- config/sst_check_python.m4
Fix for Py2 version report sent to stderr instead of stdout was not reporting in core configure report.
> Fix for Py2 version report sent to stderr instead of stdout

- Makefile.am
- configure.ac
- share/Makefile.am
- share/SSTConfig.cmake.in
This exports a CMake config file compatible with `find_package` for CMake build systems.
> Export a CMake configuration for downstream projects

- src/sst/core/configGraph.cc
- src/sst/core/configGraph.h
- src/sst/core/factory.cc
- src/sst/core/model/python2/pymodel.cc
- src/sst/core/model/python2/pymodel.h
- src/sst/core/model/python3/pymodel.cc
- src/sst/core/model/python3/pymodel.h
- Added check for multiple use of ports (fixes issue #530)
- Moved component id assignment into ConfigGraph from the python model
- Moved check for duplicate Component names into graph generation from
CponfigGraph::checkForStructuralErrors().  This was done because of
the extra memory requirement to do the check after the fact when
dealing with large graphs.
> Minor cleanup of graph generation.

- src/sst/core/interprocess/sstmutex.h
- src/sst/core/mempool.h
- src/sst/core/rankSyncParallelSkip.cc
- src/sst/core/threadsafe.h
Update intrinsics for ThunderX2 (aarch64). 
Tested on mayer (devpack-gnu7/20200125) with four nodes. Note that, on mayer, there is a problem with openmpi and parmetis when linking.
```
1) autotools      4) binutils/2.33.1   7) bzip2/1.0.6     10) numactl/2.0.12  13) openucx/1.7.0   16) pnetcdf/1.11.1  19) parmetis/4.0.3  22) superlu/5.2.1       25) fftw/3.3.8             28) mayer/sst-base
2) cmake/3.14.5   5) gnu7/7.2.0        8) xz/5.2.4        11) hwloc/1.11.11   14) openmpi4/4.0.2  17) phdf5/1.10.5    20) metis/5.1.0     23) superlu_dist/5.4.0  26) singularity/3.5.3
3) git/2.19.2     6) zlib/1.2.11       9) yaml-cpp/0.6.2  12) pmix/2.2.3      15) netcdf/4.6.3    18) cgns/3.4.0      21) openblas/0.3.4  24) boost/1.72.0        27) devpack-gnu7/20200125
```
simpleElementExample, merlin …
> First Attempt at aarch64

- src/sst/core/eli/elementinfo.cc
- src/sst/core/eli/elementinfo.h
- src/sst/core/eli/elibase.cc
- src/sst/core/statapi/statbase.h
Intel does not generate symbols for functions or variables that are only found in header files. It is the only compiler to do so.  This requires us to force instantiation of certain types in the source files. 
This fixes Intel compilers via two steps:
1. A macro is provided to force registration in source fields
1. An undefined reference is generated automatically if the instantiate macro is missing
> Add extra hooks for registering components with intel

- src/sst/core/rng/uniform.h
Fixes a bug in SSTUniformDistribution where the 0th-bin may not get entries generated by the underlying RNG.
> Fixes a Bug in UniformDistribution where bin-0 may not get entries

- src/sst/core/testingframework/sst_unittest.py
- src/sst/core/testingframework/sst_unittest_support.py
Moving test to check for existence of OpenMPI so that it does not generate errors on rank=1 tests in Jenkins.   Also changed how we compute the numa_param.  Lastly added some support code to allow tests to get the diff file on compares.
> Moving MPI check to only be required if Ranks > 1

- src/sst/core/model/python/pymacros.h
Only tp_vectorcall is needed in 3.9.
> Update pymacros for Python 3.9

- src/sst/core/testingframework/sst-test-core
- src/sst/core/testingframework/sst-test-elements
- src/sst/core/testingframework/sst_test_engine_loader.py
- src/sst/core/testingframework/test_engine.py
Move the python version checks for the new test frameworks to a centralized location.
> New test frameworks - Centralize python version check

- src/sst/core/testingframework/sst_unittest.py
Change to the test frameworks to find the add the path to the sst executable.  Necessary for when the testing frameworks is run and is not in the users path.
> Change to support running the test frameworks if sst is not in the path

- tests/testsuite_default_sstinfo.py
Fix for the sst-info test not working properly if the sst binary path is not in the users PATH env settings.
> Fix sst-info test run if sst/bin is not in users path

- src/sst/core/testingframework/sst_unittest.py
Adding a return of the command string used when calling run_sst() for the test frameworks.
> Testing Frameworks: Return launch string used for run_sst()

- src/sst/core/unitAlgebra.cc
Fix a GCC 9.2 compile warning.
> Change runtime_error Catch to a Reference

- src/sst/core/baseComponent.h
- src/sst/core/exit.cc
- src/sst/core/exit.h
- src/sst/core/main.cc
- src/sst/core/simulation.cc
- src/sst/core/simulation.h
Fixed an issue where the wrong simulated time was reported in multirank runs when there were no links cut across ranks.
> Fix issue with wrong reported simulated time in some corner cases

- src/sst/core/configGraph.cc
- src/sst/core/params.cc
Enabled error for case of two links connected to same port.  Also fixed error in Params serialization.
> More sst11 cleanup

- src/sst/core/rng/constant.h
- src/sst/core/rng/discrete.h
- src/sst/core/rng/distrib.h
- src/sst/core/rng/expon.h
- src/sst/core/rng/gaussian.h
- src/sst/core/rng/marsaglia.cc
- src/sst/core/rng/marsaglia.h
- src/sst/core/rng/mersenne.cc
- src/sst/core/rng/mersenne.h
- src/sst/core/rng/poisson.cc
- src/sst/core/rng/poisson.h
- src/sst/core/rng/uniform.h
- src/sst/core/rng/xorshift.cc
- src/sst/core/rng/xorshift.h
Renames distributions in the SST RNG core, removing SST prefixes from names. This has backwards compatibility until deprecation decisions are made. Addresses concerns identified in Issue #625.
> Migrates SST Random Distributions to new names without the SST Prefix

- src/sst/core/rng/marsaglia.cc
- src/sst/core/rng/mersenne.cc
- src/sst/core/rng/rng.h
- src/sst/core/rng/xorshift.cc
This enforces that RNGs never produce a value that equals 1.0 during generation of a double. The range of values is [0,1) otherwise the code will loop and generate an alternative. This is requested in Issue #629 and is an extremely unlikely event.
> Check that RNG never produce a value that equals 1.0

- src/sst/core/testingframework/Makefile.inc
- src/sst/core/testingframework/sst-test-core.in
- src/sst/core/testingframework/sst-test-elements.in
Uses SST's Python detection scripts to populate `sst-test-core` and `sst-test-elements` scripts (which are installed in `bin`).
> Utilize Python Detection to Populate SST Core/Element Test Loaders

- src/sst/core/testingframework/Makefile.inc
PR #683 changed the `sst-test-core` and `sst-test-elements` launch scripts be dynamically created and set the bash shebang to use the python version that SST was built with.  This change works fine.
However, the PR #683 also broke the --enable-testframework-dev feature used to develop features for the test frameworks.  This feature created symbolic links to the launching scripts so that they did not have to be copied to the install dir in order to test every frameworks change.  
This PR fixes the issue.
> Fixing --enable-testframework-dev feature to work again

- src/sst/core/elemLoader.cc
- src/sst/core/elemLoader.h
- src/sst/core/sstinfo.cc
Eliminates use of `lt_` functions for dynamic loading. This overhauls some basic capability and works with SST loading capabilities (at the cost of some generality).
> Utilize basic dlopen functionality to work around needing libtldl

- autogen.sh
- configure.ac
- src/sst/core/Makefile.am
Removes `libltdl` generation and integration with SST core.
> Remove libltdl directory creation

- scripts/clang-format-test.sh
Providing `-i` will ask clang-format to make the changes for you.  
I tested this with `--format-exe` but bash is not something I'm comfortable doing input parsing with so an extra set of eyes would be nice. 
@allevin I'm picking you since I think you know bash better than most of us.
> Changing the clang-format script to accept the `-i` option.

- src/sst/core/sstinfo.cc
Removes libltdl header from SST Info.
> Remove libltdl Header from SST Info

- .github/workflows/PR_clang-format_test.yml
This PR will add a Github Actions script that runs on PR creation or commit to a PR.  It will clone the repo on Github's test systems and then run clang-format v12.  It will set labels and add appropriate comments based upon testing.  It will also set/remove the AT: WIP flag to lockout Autotester testing if the format test fails.
> Adding GHA clang-format test

- README.md
Should fix #706, I just tested with the cmake build and with the autotools build in a centos container and both pick up the system zlib.
> Add zlib-devel to centos build instructions

- src/sst/core/CMakeLists.txt
This missing header stopped macro from compiling with the CMake build of core.
> Didn't install a header needed by macro

- experimental/.gitlab-ci.yml
Initial file for adding Gitlab CI.  This will build core in a centos 8 container with zlib and openmpi 4.0.5.  Feedback is welcome for more tests to add.
> Add gitlab ci

- configure.ac
Removes the include of base directories that can affect Apple XCode 12.5 builds.
> Fix include paths which can affect Apple XCode 12.5 with new C++ Compilers

- configure.ac
Addresses issue in #679 where flags and compacted together without spaces, leading to errors.
> Change Handling of Optimization and Profiling Flags in Configure

- src/sst/core/cfgoutput/jsonConfigOutput.cc
This fixes a small spelling mistake noted in Issue #732.  This was found during initial testing for the forthcoming JSON graph reader.  I know its a nit, but we're using the current JSON output as the initial JSON format for the forthcoming reader implementation.
> Fix for Issue #732; revising spelling of components

- experimental/cmake_configure_files/sst_config.h.in
- src/sst/core/CMakeLists.txt
- src/sst/core/config.cc
- src/sst/core/testElements/CMakeLists.txt
- src/sst/core/testElements/message_mesh/CMakeLists.txt
- the json model wasn't linked into the exe
- one of the tests wasn't compiled in the cmake build
- changed config.cc to use ifdef for mpi detection to mirror the rest of
the core
- changed the cmake generation of sst_config.h to define SST_HAVE_MPI 1
just in case others try to do #if ... instead of #ifdef
> Fixes to the cmake build

- config/sst_enable_perf_tracking.m4
- configure.ac
- src/sst/core/baseComponent.cc
- src/sst/core/baseComponent.h
- src/sst/core/clock.cc
- src/sst/core/event.cc
- src/sst/core/event.h
- src/sst/core/simulation.cc
- src/sst/core/simulation_impl.h
- src/sst/core/sync/rankSyncParallelSkip.cc
- src/sst/core/sync/rankSyncSerialSkip.cc
- src/sst/core/sync/syncManager.cc
- src/sst/core/sync/syncQueue.cc
- src/sst/core/testElements/Makefile.inc
- src/sst/core/testElements/coreTest_PerfComponent.cc
- src/sst/core/testElements/coreTest_PerfComponent.h
- tests/Makefile.inc
- tests/refFiles/test_PerfComponent.out
- tests/test_PerfComponent.py
- tests/testsuite_default_PerfComponent.py
This is a manual rebase to remove extra commits from PR #734 In addition, the naming for message size accounting has been simplified to just be called `messageXferSize`   Original PR comments reproduced below for convenience:
---------------------------------------
Adds a significant amount of performance and event tracking data. These features are DISABLED by default and only enabled via the --enable-perf-tracking option for the configure script. 
Enables tracking of simulator performance and component runtime. Options include component clock handler runtimes, openMPI synchronization overhead, and event handling. Communication sizes and information are also tracked. Tracking resolution can be implemented in nanosecond resolution or microsecond depending on individual workload. Slight …
> New perf manual rebase

- src/sst/core/cfgoutput/jsonConfigOutput.cc
Fix for Issue #777 
The fix inserts two tests into the `jsonConfigOutput.cc`.  When outputting parallel configurations where individual ranks do not have links and/or components, the modification outputs empty objects in order for the JSON model parser to correctly ingest the parallel configuration.  
This was tested against the `test_ParamComponent.py` using the following: 
Model output:
```
mpirun --hostfile output.txt -n 7 sst --run-mode=init --output-json=foo.json --parallel-output=1 test_ParamComponent.py
```
Model input:
```
mpirun --hostfile output.txt -n 7 sst --run-mode=init --parallel-load foo.json
```
> Outputting empty components and links for ranks that do not have components and/or links

- src/sst/core/baseComponent.cc
- src/sst/core/baseComponent.h
- src/sst/core/testElements/coreTest_PerfComponent.cc
- tests/testsuite_default_PerfComponent.py
This removes the redundant registerClockHander() call that was once required to have performance counters track an element's activity. This functionality was merged into the existing registerClock() function.  
In addition, the test for the PerfCounters needed to be modified for build configurations that enable perf counters *only* Some component naming has changed (independent of this PR) and the test needed to know where to find the correct values
> Streamlining the interface to Perf counters by removing redundant registerClockHandler call

- src/sst/core/cfgoutput/dotConfigOutput.cc
- src/sst/core/cfgoutput/dotConfigOutput.h
I noticed that the dot graph output was only handling first order subcomponents, and not displaying subcomponents of subcomponents or so on. Updated the code to be recursive for subcomponent dot graph output
> Recurse subcomponents

- src/sst/core/baseComponent.h
- src/sst/core/event.cc
- src/sst/core/event.h
- src/sst/core/link.cc
- src/sst/core/link.h
- src/sst/core/module.h
- src/sst/core/testElements/coreTest_Module.h
- Deprecated old module ELI in favor of using Module APIs
- Moved NullEvent into core private API and added EmptyEvent
> Deprecation cleanup

- src/sst/core/Makefile.am
- src/sst/core/baseComponent.cc
- src/sst/core/bootshared.cc
- src/sst/core/cfgoutput/pythonConfigOutput.cc
- src/sst/core/elemLoader.cc
- src/sst/core/env/envquery.cc
- src/sst/core/heartbeat.cc
- src/sst/core/main.cc
- src/sst/core/model/python/pymodel.cc
- src/sst/core/model/python/pymodel_comp.cc
- src/sst/core/output.cc
- src/sst/core/rng/marsaglia.h
- src/sst/core/rng/mersenne.h
- src/sst/core/rng/sstrng.h
- src/sst/core/rng/xorshift.h
- src/sst/core/simulation.cc
- src/sst/core/sstregistertool.cc
- src/sst/core/statapi/statfieldinfo.cc
- src/sst/core/statapi/statoutputcsv.cc
- src/sst/core/statapi/statoutputtxt.cc
- src/sst/core/stringize.cc
- src/sst/core/stringize.h
- src/sst/core/testElements/coreTest_DistribComponent.cc
- src/sst/core/testElements/coreTest_LookupTableComponent.cc
- src/sst/core/testElements/coreTest_RNGComponent.h
- src/sst/core/testElements/coreTest_StatisticsComponent.h
Added format_string() function and changed all sprintf() call to use either format_string() or snprintf().  Also marked sstrng.h deprecated.
> Remove use of sprintf

- src/sst/core/event.cc
- src/sst/core/simulation.cc
- src/sst/core/simulation_impl.h
Issue #808; Fixing issues in crashes when perf-tracking and profiling are enabled.  
Original patches from @pdbj
- https://github.com/pdbj/sst-core/commit/5dc3bd3e27801cbd81e655d28a137c6f398ee24e
- https://github.com/pdbj/sst-core/commit/7410872dc82011af65d1a4aa2f5a5afbe3adef44
Both patches have been squashed into a single commit then cleansed with clang-format-12
> Fix for Issue #808

- src/sst/core/baseComponent.cc
- src/sst/core/baseComponent.h
Added Simulation_impl pointer to BaseComponent and moved all time critical calls over to use the pointer instead of Simulation::getSimulation().
> Base Component Simulation pointer

- src/sst/core/config.cc
- src/sst/core/main.cc
- src/sst/core/model/python/pymodel.cc
- Change command line option --num_threads to --num_threads.  Fixes #871
- Fix setting of threads in the Python input file.  Fixes #872
> Threading option fixes.

- src/sst/core/Makefile.am
- src/sst/core/baseComponent.cc
- src/sst/core/baseComponent.h
- src/sst/core/component.h
- src/sst/core/config.cc
- src/sst/core/eli/elementinfo.cc
- src/sst/core/eli/elementinfo.h
- src/sst/core/eli/elibase.h
- src/sst/core/eli/profilePointInfo.h
- src/sst/core/factory.cc
- src/sst/core/factory.h
- src/sst/core/model/element_python.cc
- src/sst/core/profile/clockHandlerProfileTool.cc
- src/sst/core/profile/clockHandlerProfileTool.h
- src/sst/core/profile/componentProfileTool.cc
- src/sst/core/profile/componentProfileTool.h
- src/sst/core/profile/eventHandlerProfileTool.cc
- src/sst/core/profile/eventHandlerProfileTool.h
- src/sst/core/profile/profiletool.cc
- src/sst/core/profile/profiletool.h
- src/sst/core/profile/syncProfileTool.cc
- src/sst/core/profile/syncProfileTool.h
- src/sst/core/simulation.cc
- src/sst/core/simulation_impl.h
- src/sst/core/sst_types.h
- src/sst/core/ssthandler.h
- src/sst/core/subcomponent.h
- Can now declare profile points using SST_ELI_DOCUMENT_PROFILE_POINTS macro
- Added ComponentCodeSegmentProfileTool classes
- Changed --enable-profiling argument formatting to be more flexible to specify component profile points
Also fixed an issue in element_python.cc related to changes in the Cpython API.
> Made profiling points available in Components and SubComponents

- src/sst/core/interfaces/stdMem.h
This is a fix for Issue #886 whereby getSuccess always returns true.  Changing the logic for getSuccess such that it correctly returns true OR false.  Originally reported by @PhilippKasgen
> adding fix for Issue #886; getSuccess would always return true

- src/sst/core/CMakeLists.txt
- src/sst/core/profile/CMakeLists.txt
git clone https://github.com/sstsimulator/sst-core.git
cd sst-core && mkdir build && cd build
cmake ../experimental
make -j32
OLD BEHAVIOR
sstsim.x and other targets fail to build with linking errors
NEW BEHAVIOR
build completes successfully
> cmake builds

- experimental/CMAKE_README.md
- experimental/CMakeLists.txt
This bumps the c++ version requirements up to C++ 17 to match the recent bump in the traditional makefiles.  This is a fix for Issue #922.  We also bump the date on the copyright notice in the README.
> adding requirement for C++ 17 in SST-Core CMake infrastructure

- src/sst/core/mempool.cc
Fix for https://github.com/sstsimulator/sst-core/issues/934
> Fix unit to int in getMemPoolUsage

- src/sst/core/Makefile.am
I can't find the PR(s) where ParMETIS was removed, if it was ever present.
This should not affect and is separate from anything #878 touches.
> Remove last bits of ParMETIS

- .github/workflows/PR_cmake-format_test.yml
For #716, a follow-up to #963.  Apparently we are using an older form of the GitHub script language and I blindly updated the version for the CMake format checker.  The path also wasn't updated to the experimental location.
There is a non-syntax update that needs to be made, which is that the action only runs `cmake-format --check`, not the additional and different `cmake-lint`, but shouldn't be solved in this PR.
> Fixes for cmake-format GitHub Action

- experimental/cmake/sst.cmake
- experimental/cmake_configure_files/sst_config.h.in
- src/sst/core/testElements/CMakeLists.txt
> Fix tests broken under CMake compilation

- src/sst/core/decimal_fixedpoint.h
> Add missing cstdint include for GCC 13

- .github/workflows/PR_cmake-format_test.yml
See the comments starting at https://github.com/sstsimulator/sst-core/pull/974#issuecomment-1638947397.  CI will be broken until this is merged.
> Update cmake-format-lint-action version

- experimental/CMakeLists.txt
- share/CMakeLists.txt
* Bump CMake project version to 13.0.0
* Minimum required version of Python now matches autotools build
* Set C++ standard in a single location
> CMake update grabbag

- src/sst/core/eli/attributeInfo.h
- src/sst/core/eli/paramsInfo.h
- src/sst/core/eli/portsInfo.h
- src/sst/core/eli/profilePointInfo.h
- src/sst/core/eli/statsInfo.h
- src/sst/core/eli/subcompSlotInfo.h
This is needed when at least one of the two types is a dependent type. For example, while `std::conditional<true, int, float>::type` is fine, when `T` is a template parameter, `typename std::conditional<true, int, T>::type` is necessary.
These replacements are entirely inside of the ELI macros that use them, and allow us to use template classes in our element hierarchies.
Erase this information and put your Pull Request comments here
---
Instructions for Issuing a Pull Request to sst-core
---------------------------------------------------
1 - Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-core
2 - Verify that Source branch is up to date with the devel branch of sst-core
3 - After submitting your Pull Request:
* Automatic Testing will commence in a …
> Add `typename` to some uses of std::conditional.

- configure.ac
We already know from
```bash
printf "%38s : %s (%s)\n" "Found Python" "$PYTHON_EXE" "$PYTHON_VERSION"
```
what Python version was found, and Python 2 would have been trapped in the configure process much earlier than the warning print.
---
Redo of https://github.com/sstsimulator/sst-core/pull/988.
> Remove outdated Python 2/3 printing from configure.ac

- src/sst/core/eli/elibase.h
This resolves #1005.
Imagine the following code:
```c++
template <class Component>
struct MyComponentBase : public Component {
SST_ELI_DECLARE_NEW_BASE(Component, MyComponentBase);
// tools that help us with SST::Component interfaces
};
struct MyComponent : MyComponentBase<SST::Component> {
// A custom component
};
struct MyRouter : MyComponentBase<SST::Merlin::Router> {
// A merlin router implementation
};
```
In this context, inside the `SST_ELI_DECLARE_NEW_BASE`, the `BuilderInfo` is a dependent name in the `addDerivedInfo` template function, and can't be found without qualification. The qualified name is `__LocalEliBase::BuilderInfo` and it needs a `typename` pre-C++20.
This patch adds that typename to support this template pattern. This pattern allows us to write utility code that …
> Fix for `SST_ELI_DECLARE_NEW_BASE` when `BuilderInfo` is a dependent name.

- src/sst/core/interfaces/simpleNetwork.h
- src/sst/core/interfaces/stdMem.h
- src/sst/core/sst_types.h
- src/sst/core/statapi/statgroup.cc
These defines are used like `PRIu64` etc. for typedefs in elements.
There's also a fix for an unused return value.
> String format specifiers for typedefs

- src/sst/core/model/python/pymodel_unitalgebra.cc
- src/sst/core/unitAlgebra.cc
- src/sst/core/unitAlgebra.h
- tests/refFiles/test_UnitAlgebra.out
- tests/test_UnitAlgebra.py
Also add functions for pretty-printing UnitAlgebra in python
> Fix issue where python passed rounded UnitAlgebras through parameters

- src/sst/core/interfaces/stdMem.h
This is related to #1001. Introduces an interface so we can leapfrog sst-core and sst-elements to ensure builds continue to pass as we deal with this pernicious memory leak.
> Add interface for accessing CustomReq/Resp data

- configure.ac
- share/CMakeLists.txt
- share/Makefile.am
- share/SSTConfigVersion.cmake.in
With this commit SST can be found with version restrictions in CMake
find_package(SST 13 REQUIRED)
Before this commit cmake would error with:
Could not find a configuration file for package "SST" that is compatible
with requested version "13".
The following configuration files were considered but not accepted:
/lib/cmake/SST/SSTConfig.cmake, version: unknown
(The code of this change was made by one of my colleagues, who allowed me to make a PR for this.)
> Add SSTConfigVersion.cmake to allow cmake find_package with version

- src/sst/core/statapi/statbase.h
I get a compiler error when trying to call `addDataNTimes` from anywhere:
```
In file included from /opt/sst/include/sst/core/baseComponent.h:23,
from /opt/sst/include/sst/core/component.h:15,
from ../../../../../src/sst/elements/memHierarchy/cacheController.h:26,
from ../../../../../src/sst/elements/memHierarchy/cacheController.cc:21:
/opt/sst/include/sst/core/statapi/statbase.h: In instantiation of 'void SST::Statistics::Statistic<T>::addDataNTimes(uint64_t, InArgs&& ...) [with InArgs = {int}; T = long unsigned int; uint64_t = long unsigned int]':
../../../../../src/sst/elements/memHierarchy/cacheController.cc:207:37:   required from here
/opt/sst/include/sst/core/statapi/statbase.h:392:32: error: 'addData_impl_Ntimes' was not declared in this scope, and no declarations were found by …
```
> Fix compiler error when calling addDataNTimes

- src/sst/core/config.cc
- src/sst/core/main.cc
- src/sst/core/simulation.cc
- src/sst/core/testElements/coreTest_Component.cc
- src/sst/core/testElements/coreTest_Component.h
- src/sst/core/testingframework/sst_unittest_support.py
- tests/Makefile.inc
- tests/refFiles/test_Component_time_overflow.out
- tests/test_Component_time_overflow.py
- tests/testsuite_default_Component.py
Adds a check to make sure time does not go backwards within a simulation object.  It will call fatal() if it detects a time fault. The most likely cause is actually that the 64-bit core time variable overflowed.
Also includes a change to serialize threads in creating Links because interleaving the creation of Links leads to very long deletion times when there are a large number of links.
> Time fault

- src/sst/core/cfgoutput/pythonConfigOutput.cc
- src/sst/core/cfgoutput/pythonConfigOutput.h
- src/sst/core/model/python/pymodel.cc
- Fixed issue when using pushNamePrefix() with empty string; function will no longer add . to name for empty string prefixes
- Changed python config output so that it now uses the actual Link name in the python instead of name based on link ID
> Fixed some python issues

- src/sst/core/configGraphOutput.h
- src/sst/core/cputimer.h
- src/sst/core/event.h
- src/sst/core/exit.h
- src/sst/core/linkPair.h
Documentation for the files:
1. configGraphOutput.h
2. cputimer.h
3. event.h
4. exit.h
5. linkPair.h
> Doxygen Documentation - Small Updates

- src/sst/core/model/python/pymodel_unitalgebra.cc
- src/sst/core/unitAlgebra.cc
- src/sst/core/unitAlgebra.h
- tests/test_UnitAlgebra.py
Closes #1037
Here is a proposal for adding exceptions to the core public API.  Doxygen is missing until we decide on the form of exceptions.
Thoughts:
- Since these exceptions are specific for `UnitAlgebra`, I've added them inside the `UnitAlgebra` class rather than just the header.
- There is a base `UnitAlgebraException` in case a consumer (elements, some other code) wants to catch a more generic exception type rather than one of the more specific types.
- The base `UnitAlgebraException` inherits from `logic_error` rather than `exception` since these are fundamentally not runtime errors.
- As a development guideline, it seems like reasons/messages given by C++ exceptions should be actionable directly Python side: the message passed to `PyErr_SetString` should always be …
> Use exceptions for UnitAlgebra errors

- src/sst/core/action.h
- src/sst/core/configGraphOutput.h
- src/sst/core/cputimer.h
- src/sst/core/event.h
- src/sst/core/exit.h
- src/sst/core/linkPair.h
- src/sst/core/sstinfo.h
- src/sst/core/stringize.h
- src/sst/core/timeConverter.h
- src/sst/core/timeLord.h
- src/sst/core/unitAlgebra.h
Files:
- action.h
- sstinfo.h
- stringize.h
- timeConverter.h
- timeLord.h
- unitAlgebra.h
> Additional documentation for 6 files

- src/sst/core/testingframework/sst_test_engine_loader.py
- src/sst/core/testingframework/sst_unittest.py
- src/sst/core/testingframework/sst_unittest_parameterized.py
- src/sst/core/testingframework/sst_unittest_support.py
- src/sst/core/testingframework/test_engine.py
- src/sst/core/testingframework/test_engine_junit.py
- src/sst/core/testingframework/test_engine_support.py
- src/sst/core/testingframework/test_engine_unittest.py
- tests/testsuite_default_Links.py
- tests/testsuite_testengine_testing.py
This removes all of the testing infrastructure that tries to distinguish between Python 2 and 3.  It also removes the minimum Python version check in favor of the one performed by Autotools at configure time.
> Remove Python 2 testing infrastructure

- src/sst/core/sstinfo.cc
- src/sst/core/testingframework/sst_unittest.py
- tests/testsuite_default_sstinfo.py
Add a unit test for sst-info interactive mode and add a quit command
> SST-info Update

- .github/workflows/PR_clang-format_test.yml
- .github/workflows/PR_cmake-format_test.yml
- .pre-commit-config.yaml
This updates the version of every Action to the latest major version.  The primary reason to do this is that older versions will no longer be supported by GitHub as they run unsupported versions of Node, particularly `github-script`.
Updating `github-script` requires modifications when going from v4 to v5, as the underlying GitHub API in JavaScript changed.  (The link is in the commit body.)  Going from v5 to v7 is just version updates in the underlying Node runtime.
> Update GitHub Actions versions

- src/sst/core/config.cc
- src/sst/core/main.cc
- src/sst/core/output.h
- src/sst/core/realtime.cc
- src/sst/core/realtime.h
- src/sst/core/testingframework/sst_unittest.py
- src/sst/core/testingframework/sst_unittest_support.py
- tests/testsuite_default_Checkpoint.py
- tests/testsuite_default_RealTime.py
Fix bug in real time interval tracking
Fix so sdl file is checked after its name is changed in parallel load
Change MPI test utility to include stderr output as they do in serial tests
Exit simulation if the check for the SDL file fails
Add --checkpoint-period back in
> Realtime bug fix and other fixes

- src/sst/core/testingframework/sst_unittest_support.py
This deduplicates the filtering and sorting code in `testing_compare_filtered_diff`.
> test framework: factor out reading and filtering lines from test output

- src/sst/core/testingframework/sst_unittest.py
- tests/testsuite_default_Checkpoint.py
- tests/testsuite_default_Component.py
- tests/testsuite_default_Links.py
- tests/testsuite_default_MemPoolTest.py
- tests/testsuite_default_Module.py
- tests/testsuite_default_Output.py
- tests/testsuite_default_ParamComponent.py
- tests/testsuite_default_PerfComponent.py
- tests/testsuite_default_RNGComponent.py
- tests/testsuite_default_RealTime.py
- tests/testsuite_default_Serialization.py
- tests/testsuite_default_SharedObject.py
- tests/testsuite_default_StatisticsComponent.py
- tests/testsuite_default_SubComponent.py
- tests/testsuite_default_UnitAlgebra.py
- tests/testsuite_default_config_input_output.py
- tests/testsuite_default_partitioner.py
- tests/testsuite_default_sstinfo.py
- tests/testsuite_testengine_testing.py
The implementation of `initializeTestModule_SingleInstance()` is essentially the same across all of the `SSTTestCase` subclasses.  There's no need to re-implement them in each class.  We can cut ~15 lines from each of the 19 `testsuite_default_*.py` files.
> Remove redundant initializeTestModule_SingleInstance() methods

- src/sst/core/testingframework/sst_unittest_support.py
Closes #1120
-------------
Corrects `getbool` to `getboolean` to fix `sstsimulator_conf_get_value_bool` for getting booleans from the SST configuration file
> Fix sstsimulator_conf_get_value_bool

- .github/workflows/PR_clang-format_test.yml
This fixes the error in the `clang-format` part of CI:
```
Traceback (most recent call last):
File "/run-clang-format.py", line 25, in <module>
from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
```
See https://github.com/kokkos/kokkos/pull/7295 for another example.
This is not the version of `clang-format` used, which is specified by `clangFormatVersion: 12` (see line 75).
All PRs on core will fail until this is merged.
Redo of https://github.com/sstsimulator/sst-core/pull/1126
> Update and pin version of clang-format-lint-action

- src/sst/core/testingframework/test_engine_unittest.py
This fixes warnings like:
```
sst-core/bin/../libexec/test_engine_unittest.py:327: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
```
The version conditional is because https://docs.python.org/3/library/datetime.html#datetime.UTC wasn't added until Python 3.11.
> Python 3.11: Update datetime command for current UTC time

- tests/testsuite_default_RealTime.py
Tests were sending a signal too quickly for the slower VMs and containers to catch.
> Fix RealTime tests

- src/sst/core/testingframework/sst_unittest_support.py
See https://docs.python.org/3/library/tarfile.html#tarfile-extraction-filter for more information.
This silences the warning:
```
/usr/lib/python3.12/tarfile.py:2221: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
```
> Update tar extraction command for Python 3.12 and newer

- src/sst/core/testingframework/sst_unittest_support.py
We are deprecating `testing_is_PIN2_used()` at some future release.  This PR simply adds a warning to any code that calls this function.
> deprecate testing_is_PIN2_used()

- src/sst/core/testingframework/sst_unittest_support.py
`host_os_get_*()` : Eliminate the ones that are just wrapping a Python function in favor of the Python function. Most tests at most have to make a distinction between osx & linux. Occasionally Ubuntu vs RHEL needs to be treated differently but only w.r.t. Pin in my experience.
> deprecate simple host_os_get_* methods

- src/sst/core/testingframework/sst_unittest_support.py
This PR fixes some issues but not all with testing under OpenMPI 5.x.
> Add handling for output file naming conventions in OpenMPI 5.0.x

- src/sst/core/testingframework/sst_unittest_support.py
* sst_core_config_include_file_get_value_int()
* sst_core_config_include_file_get_value_str()
* sst_elements_config_include_file_get_value_int()
* sst_elements_config_include_file_get_value_str()
* sstsimulator_conf_get_value_int()
* sstsimulator_conf_get_value_str()
* _get_sst_config_include_file_value()
> deprecate type-specific configuration getters; add generic replacement functions

- src/sst/core/testingframework/sst_unittest_support.py
`testing_check_is_scenario_filtering_enabled()` should be internal. It's only used in `skip_on_scenario()`
I feel this change is small and localized enough we don't need to deprecate it first.  There are no references to it anywhere besides its usage in `skip_on_scenario()`.  Thoughts?  @gvoskuilen @feldergast 
Closes https://github.com/jmlapre/sst-core/issues/8
> make helper function internal

- src/sst/core/testingframework/sst_unittest_support.py
`os.path.isfile("/etc/rocky-release", " ")` is incorrect and shouldn't have the additional `" "` passed to it.
> Fix call to os.path.isfile()

- src/sst/core/testingframework/sst_unittest_support.py
- src/sst/core/testingframework/test_engine_support.py
Passing `timeout_sec` via `**kwargs` allows us to override default timeouts.
Not all os_cmds use the `OSCommand.run()` call, however.
Closes https://github.com/jmlapre/sst-core/issues/18
> Allow overriding default timeout in os_cmd() calls

- src/sst/core/testingframework/sst_unittest.py
- src/sst/core/testingframework/sst_unittest_support.py
- src/sst/core/testingframework/test_engine.py
* sstsimulator_conf_get_value_str()
* host_os_get_num_cores_on_system()
Closes https://github.com/jmlapre/sst-core/issues/23
> Remove calls to deprecated functions

- src/sst/core/simulation.cc
- src/sst/core/sync/syncManager.cc
- src/sst/core/testElements/coreTest_Component.h
- Fixes #1156 - Initial Sync interval needed to take Checkpoint time into account.
- Fixes #1157 - Moved barrier for Exit restart to the proper place.
> Bug fixes for parallel checkpointing.

- pyproject.toml
- scripts/format-diff
- src/sst/core/model/xmlToPython.py
- src/sst/core/testingframework/sst_test_engine_loader.py
- src/sst/core/testingframework/sst_unittest.py
- src/sst/core/testingframework/sst_unittest_parameterized.py
- src/sst/core/testingframework/sst_unittest_support.py
- src/sst/core/testingframework/test_engine.py
- src/sst/core/testingframework/test_engine_globals.py
- src/sst/core/testingframework/test_engine_junit.py
- src/sst/core/testingframework/test_engine_support.py
- src/sst/core/testingframework/test_engine_unittest.py
- tests/testsuite_default_RealTime.py
In the test framework, the use of custom classes to extend `unittest` (and the use of `unittest` in general) makes it difficult to understand what objects are getting passed around.  This PR adds an initial set of (incomplete) type annotations and a `mypy` configuration.  `mypy` will run type checking just like a compiler for functions and methods that have their signatures annotated with types.
At least for the test framework, this is also part of https://github.com/sstsimulator/sst-core/issues/987.
This PR does not enable checking the type annotations with `mypy` via `pre-commit`, since the annotations are incomplete and may still be wrong in a few places while they are being added.  It's easier to iterate on the annotations and the configuration rather than do everything all at once.
> Add initial set of Python type annotations

- src/sst/core/model/xmlToPython.py
- src/sst/core/testingframework/sst_test_engine_loader.py
- src/sst/core/testingframework/sst_unittest_parameterized.py
- src/sst/core/testingframework/test_engine.py
The docstring of `testingframework/test_engine.py/discover_and_run_tests()` states that it returns the status code to be used for exiting, and presumably `testingframework/sst_test_engine_loader.py/startup_and_run()` would use this when calling `sys.exit(...)`.  This was not the case, so it fixes that.
This should be safe since we don't consider these files to be part of the public testing API.
The other changes are small fixes for type annotations.
> Python: update logic between discover_and_run_tests and startup_and_run

- src/sst/core/testingframework/test_engine.py
The missing imports for `multiprocessing` and `OSCommand` are actual bugs.
> Python: add type annotations to testingframework/test_engine.py

- src/sst/core/sstinfo.cc
Fixes issue where filtering sst-info on a specific element within a library would not generate output.
> Fix bug in sst-info filtering

- .clang-format
- src/sst/core/Makefile.am
- src/sst/core/config.cc
- src/sst/core/config.h
- src/sst/core/configBase.cc
- src/sst/core/configBase.h
- src/sst/core/from_string.h
- src/sst/core/model/python/pymodel.cc
- src/sst/core/model/python/pymodel.h
- src/sst/core/model/python/pymodel_comp.cc
- src/sst/core/model/python/pymodel_link.cc
- src/sst/core/model/python/pymodel_stat.cc
- src/sst/core/model/python/pymodel_statgroup.cc
- src/sst/core/model/python/pymodel_unitalgebra.cc
- src/sst/core/util/Makefile.inc
- src/sst/core/util/smartTextFormatter.cc
- src/sst/core/util/smartTextFormatter.h
Added the ability to turn on the Python coverage model.  Also added SmartTextFormatter class to allow better formatting of text output to console.
> Import Python Coverage

- src/sst/core/unitAlgebra.cc
While turning on STL debugging flags, it was noticed that `UnitAlgebra::trim()` sometimes reads past the end of a `0`-length string:
```
$  /home/lkillough/sstcore-14.1.0/bin/sst   /home/lkillough/sst-core/tests/test_UnitAlgebra.py
...
Initialization from numeric arguments:
/usr/include/c++/12/bits/basic_string.h:1209: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
```
After this change:
```
$  /home/lkillough/sstcore-14.1.0/bin/sst   /home/lkillough/sst-core/tests/test_UnitAlgebra.py …
```
> Handle zero-length string in UnitAlgebra::trim()

- src/sst/core/eli/elementinfo.cc
- src/sst/core/eli/elibase.cc
- Remove redundant `static` definition of `SST_ELI_COMPILED_VERSION` in `elibase.cc`
- Use:
-  `std::string`, `std::to_string` and mutable `delim`iter
- instead of
-  `std::stringstream`, `operator<<` and more complicated `bool` variable
- to create version string
- Change `#include <sstream>` to `#include <ostream>` since `std::ostream` is used but `std::stringstream` is no longer used
> Simplify SST_ELI_COMPILED_VERSION

- src/sst/core/eli/elementinfo.cc
- src/sst/core/eli/elibase.h
- Combines two separate `combineEliInfo()` implementations for types which have a `.description` field and those which don't have a `.description` field (which have a `.value` field instead)
- Uses `if constexpr( ... )` to test either `.description != nullptr` or `.value != nullptr`
- Uses `std::none_of()` with lambda to simplify the code which finds `name` matches
- Previous code used `bool` `add` local variable which shadowed `std::vector&` `add` function parameter
- Makes the second parameter a reference to `const` `vector` since it's not modified
- Makes `combineEliInfo()` a non-`static` `template` function in a header so all instantiations are merged
- `static` would put a separate copy in each translation unit
> Combine combineEliInfo() implementations

- src/sst/core/baseComponent.h
- src/sst/core/decimal_fixedpoint.h
- src/sst/core/eli/attributeInfo.h
- src/sst/core/eli/elementbuilder.h
- src/sst/core/eli/elementinfo.h
- src/sst/core/eli/paramsInfo.h
- src/sst/core/eli/portsInfo.h
- src/sst/core/eli/profilePointInfo.h
- src/sst/core/eli/simpleInfo.h
- src/sst/core/eli/statsInfo.h
- src/sst/core/eli/subcompSlotInfo.h
- src/sst/core/from_string.h
- src/sst/core/impl/timevortex/timeVortexBinnedMap.h
- src/sst/core/impl/timevortex/timeVortexPQ.h
- src/sst/core/params.h
- src/sst/core/serialization/impl/serialize_array.h
- src/sst/core/serialization/serializable.h
- src/sst/core/serialization/serialize.h
- src/sst/core/shared/sharedArray.h
- src/sst/core/shared/sharedMap.h
- src/sst/core/shared/sharedSet.h
- src/sst/core/ssthandler.h
- src/sst/core/statapi/statbase.h
- src/sst/core/statapi/statnull.h
This changes the code to use `trait_t<...>` for `typename trait<...>::type` (C++14) and `trait_v<...>` for `trait<...>::value` (C++17), and refactors the ElementBuilder to define `is_tuple_constructible_v<...>` in terms of `is_tuple_constructible<...>::value` and apply it recursively.
For serialization code which depends on Boolean traits tests, `if constexpr( ... )` is used for the `if`-tests, since the controlling expression is constant and can be optimized at compile-time, and because this allows the code in the future to use operations or access fields which are only valid for certain template arguments.
> Use _t and _v traits instead of ::type and ::value

- src/sst/core/statapi/statnull.h
Fixes a lot of warnings under clang
> Fix missed override in statnull.h

- .pre-commit-config.yaml
- pyproject.toml
- src/sst/core/testingframework/sst_unittest_support.py
- src/sst/core/testingframework/test_engine_unittest.py
- tests/test_PortModule.py
This is the last of the PRs that add type annotations to the test framework, this time adding some and fixing others in `test_engine_unittest.py`.
Since the type checker `mypy` now considers the type annotations to be valid and complete, I've enabled that they should be enforced during CI runs.  This only affects changes to the test framework itself, not core or elements tests, so most people are unlikely to encounter problems with it.
> Enforce Python type annotations in continuous integration

- src/sst/core/checkpointAction.h
- src/sst/core/exit.h
- src/sst/core/factory.h
- src/sst/core/heartbeat.h
- src/sst/core/interactiveConsole.h
- src/sst/core/simulation_impl.h
- src/sst/core/testElements/coreTest_ClockerComponent.h
- src/sst/core/testElements/coreTest_Component.h
- src/sst/core/testElements/coreTest_DistribComponent.h
- src/sst/core/testElements/coreTest_MessageGeneratorComponent.h
- src/sst/core/testElements/coreTest_ParamComponent.h
- src/sst/core/testElements/coreTest_PerfComponent.h
- src/sst/core/testElements/coreTest_PortModule.h
- src/sst/core/testElements/coreTest_RNGComponent.h
- src/sst/core/testElements/coreTest_StatisticsComponent.h
- src/sst/core/timeLord.h
This uses modern methods of deleting copy constructors and copy assignment operators, with `= delete`.
Copy assignment operators declared `void operator=()` were changed to `class& operator=()` to become a copy assignment operator as defined by the language, so that the default one can be deleted.
For some classes, a default constructor previously explicitly declared `private` to prevent its use outside of the class was removed, because the declaration of the copy constructor causes the deletion of the default constructor.
> Use modern techniques to delete copy constructors and assignment operators

- scripts/clang-format-test.sh
Detects the last version string (X.Y.Z) in the output returned by `clang-format --version` and uses that to perform version check. Also add default if string parse returns nothing. This relates to #1236.
> Fix clang-format version check

- src/sst/core/simulation.cc
While investigating Valgrind errors, I noticed this code which is much simpler and less error-prone if `std::vector<char>` is used to manage a varying-size buffer.
> Use std::vector for varying sized buffers

- src/sst/core/elemLoader.cc
- src/sst/core/eli/elementbuilder.h
- src/sst/core/eli/elementinfo.h
- src/sst/core/eli/elibase.cc
- src/sst/core/eli/elibase.h
1. Use Meyers Singletons (`static` variables local to functions which are initialized on their first call and return a reference to it; avoids `static` initialization order fiasco) instead of pointers allocated on demand.
2. Use `std::shared_ptr` for `LoadedLibraries` loaded libraries so that libraries and aliases can share the same loader pointers without memory leaks. I was prompted to do this by `valgrind`:
```
==3714114== 80 bytes in 1 blocks are definitely lost in loss record 1,155 of 1,554
==3714114==    at 0x4859047: operator new(unsigned long) (vg_replace_malloc.c:472)
==3714114==    by 0x249295: addLoader (elementinfo.h:266)
==3714114==    by 0x249295: addInfo (elementinfo.h:184)
==3714114==    by 0x249295: addInfo (statbase.h:426)
==3714114==    by 0x249295: bool …
```
> Use Meyers singletons

- src/sst/core/testingframework/test_engine_unittest.py
Updating some of our `super()` calls caused this failure.  Restore the old code for the non-concurrent testing case.
Closes #1262
> Fix #1262 by specifying intended base class

- configure.ac
Simplifies use of the generated sst_config.h by giving it an include guard.
> Add include guard to sst_config.h

- src/sst/core/impl/timevortex/timeVortexBinnedMap.cc
- src/sst/core/impl/timevortex/timeVortexPQ.cc
Reformat long TimeVortex string messages to be split across lines.
> Reformat long TimeVortex string messages to be split across lines.

- src/sst/core/baseComponent.h
- src/sst/core/factory.h
- src/sst/core/serialization/serializable_base.h
- src/sst/core/sstconfigtool.cc
- src/sst/core/statapi/statengine.h
Add `[[noreturn]]` to non-virtual functions which do not return, such as calling `Output::fatal()`.
(If the function is virtual, then `[[noreturn]]` has little benefit unless the function is marked as `final`, which is dangerous to do because SST Elements and other client code might override SST Core classes, and without a careful analysis of which functions and classes are really `final` in SST Core, it is too risky to add `final` to functions or classes, so `[[noreturn]]` is left off of virtual functions.)
> Add [[noreturn]] to non-virtual functions which do not return

- .github/workflows/PR_clang-format_test.yml
- .github/workflows/PR_cmake-format_test.yml
Fix the intentional Ubuntu 20.04 brownouts (https://github.com/actions/runner-images/issues/11101) due to end of life.
The installation of the tools on these runners doesn't actually depend on the runner itself as long as it's Linux, so this is safe.
> Update GitHub Actions runners to Ubuntu 24.04

- src/sst/core/componentInfo.cc
- src/sst/core/configGraph.h
- src/sst/core/model/python/pymodel.cc
- src/sst/core/model/python/pymodel_comp.cc
- src/sst/core/simulation_impl.h
- src/sst/core/testElements/coreTest_Checkpoint.cc
- src/sst/core/testElements/coreTest_Checkpoint.h
This fixes some Valgrind memory errors:
1. In `ConfigComponent`, `slot_num` and `statLoadLevel` were not being initialized (maybe because they only apply in some cases -- a `slot_num` comment says "Only valid for subcomponents") and when `ConfigComponent` is serialized, it causes Valgrind to report an uninitialized memory read. This change simply adds `slot_num(0)` and `statLoadLevel(0)` to the constructors to initialize them to `0` and avoid uninitialized memory reads.
2. In the `SSTPythonModelDefinition` constructor, an `argv` array is `malloc()`ed and then each of the argument pointers are separately `malloc()`ed. But then when it finishes, it only `free()`s the `argv` array, but not its individual arguments.
3. In `pymodel_comp.cc`, `compInit()` allocates a string by calling …
> Fix Valgrind memory errors

- src/sst/core/configBase.cc
This PR allows the user to specify seconds-only wall time in either S or Ss format ( e.g. >60s ). Fixes issue #1165.
ConfigBase::parseWallTimeToSeconds(...) is modified to first check if the argument is of the form S or Ss and parses the value directly. If that fails the normal path is followed.
> Allow user to specify seconds-only wall time in either S or Ss format

- src/sst/core/cfgoutput/jsonConfigOutput.cc
- src/sst/core/cfgoutput/jsonConfigOutput.h
Adds shared statistics writing from the JSON config writer.  Takes a similar approach to the Python writer.  This is the remainder of the fix for Issue #1240
> adding shared stats writing from JSON; Fix for JSON portion of Issue #1240

- src/sst/core/from_string.h
- src/sst/core/serialization/impl/serialize_array.h
- src/sst/core/serialization/serialize.h
- src/sst/core/statapi/statbase.h
- src/sst/core/statapi/statnull.h
Replace all uses of the word and type traits `fundamental` with `arithmetic`, because `fundamental` is the wrong description -- the wrong named requirement -- for its uses.
--------
In C++ nomenclature and [`<type_traits>`](https://en.cppreference.com/w/cpp/header/type_traits), there are [different type categories](https://en.cppreference.com/w/cpp/language/type):
- Integral, `std::is_integral`: All signed and unsigned integer and `char` types, including `bool`
- Floating-point, `std::is_floating_point`: `float`, `double`, `long double`, extensions like `_Float16`
- Enumeration, `std::is_enum`: Scoped (`enum class`) and unscoped (`enum`) enumeration types
- Pointer, `std::is_pointer`: A pointer to an object or function, like `T*` or `void (*)()`
- Null pointer, `std::is_null_pointer`: …
> Replace incorrect usage of std::is_fundamental with std::is_arithmetic

- src/sst/core/testingframework/sst_unittest_support.py
Will be required when turning off long-running tests in sst-elements.
> Add testing_check_is_nightly() function

- src/sst/core/Makefile.am
- src/sst/core/serialization/impl/mapper.cc
- src/sst/core/serialization/impl/serialize_array.cc
- src/sst/core/serialization/impl/serialize_array.h
- src/sst/core/serialization/objectMap.h
- src/sst/core/serialization/serialize.h
- src/sst/core/serialization/serializer.cc
- src/sst/core/serialization/serializer.h
This rewrites the array serialization, adding support for `std::array` and dynamically allocated arrays of types besides arithmetic and `enum`.
It still supports the existing wrapper classes `SST::Core:Serialization::array(ptr, size)` and `SST::Core::Serialization::raw_ptr(ptr)` which, when serialized, serialize a dynamic array and a `void*` raw pointer, respectively.
`ser& SST::Core::Serialization::array(ptr, size)` during deserialization, will get `size` and allocate `ptr` with `new ELEM_T[size]` where `ELEM_T` is the type that `ptr` points to.
`std::array<ELEM_T,SIZE>` and `ELEM_T[SIZE]`, and pointers to them, are handled with the same templated class. A pointer to a fixed array, like `int (*aptr)[10]`, will be allocated when deserialized.
-----
The old `serializer::array()` function …
> Serialize arrays, making the code much simpler and more general

- src/sst/core/interfaces/stdMem.h
Updates all classes within stdMem.h to be checkpointable (`Request`, `RequestConverter`, and `RequestHandler`), also adds a `Handler2` to `StandardMem`.
> StandardMem Serialization

- src/sst/core/serialization/impl/serialize_array.h
- src/sst/core/serialization/impl/serialize_insertable.h
- src/sst/core/serialization/impl/serialize_tuple.h
This fixes warnings about mixing `enum` and integers on GCC, and makes the `SerOption` tests uniform.
> Fix enum warnings and make SerOption tests uniform

- src/sst/core/baseComponent.cc
- src/sst/core/baseComponent.h
- src/sst/core/link.cc
- src/sst/core/link.h
- src/sst/core/objectComms.h
- src/sst/core/portModule.cc
- src/sst/core/portModule.h
- src/sst/core/serialization/impl/serialize_adapter.h
- src/sst/core/serialization/impl/serialize_array.h
- src/sst/core/serialization/impl/serialize_atomic.h
- src/sst/core/serialization/impl/serialize_insertable.h
- src/sst/core/serialization/impl/serialize_string.h
- src/sst/core/serialization/impl/serialize_tuple.h
- src/sst/core/serialization/serializable.h
- src/sst/core/serialization/serialize.h
- src/sst/core/simulation.cc
- src/sst/core/simulation_impl.h
- src/sst/core/statapi/statbase.h
- src/sst/core/sync/rankSyncParallelSkip.cc
- src/sst/core/sync/rankSyncSerialSkip.cc
- src/sst/core/testElements/coreTest_Checkpoint.cc
- src/sst/core/testElements/coreTest_Checkpoint.h
- src/sst/core/testElements/coreTest_Serialization.cc
- src/sst/core/timeConverter.h
- src/sst/core/timeLord.cc
- src/sst/core/timeVortex.h
- src/sst/core/unitAlgebra.h
Deprecates use of shared TimeConverter* objects in link/clock/simtime calls that use them
Also:
* Adds support for serializing std container pointers 
* Fixes some remaining VLA warnings
* Changes SST_FRIEND_SERIALZE to SST_FRIEND_SERIALIZE
> Deprecate use of shared TimeConverter* objects

- .git-blame-ignore-revs
- configure.ac
- src/sst/core/impl/timevortex/timeVortexPQ.cc
- src/sst/core/interfaces/stdMem.h
- src/sst/core/testElements/coreTest_ClockerComponent.h
- src/sst/core/testElements/coreTest_DistribComponent.h
- src/sst/core/testElements/coreTest_Links.h
- src/sst/core/testElements/coreTest_MessageGeneratorComponent.h
- src/sst/core/testElements/coreTest_ParamComponent.h
- src/sst/core/testElements/coreTest_PerfComponent.h
- src/sst/core/testElements/coreTest_RNGComponent.h
- src/sst/core/testElements/coreTest_StatisticsComponent.h
- src/sst/core/testElements/message_mesh/enclosingComponent.h
- src/sst/core/watchPoint.h
Add `override` for virtual functions which are overriden (as warned by `-Wsuggest-override`).
`virtual` could be removed wherever `override` was used. `override` implies `virtual`, but it was felt that leaving `virtual`, which is at the beginning, would make it more readable. If `virtual` existed before, it was not removed simply because `override` was added, but if neither `virtual` nor `override` existed and `override` applied because the function was virtual in a base class, then only `override` was added.
> Add override for virtual functions which are overriden

- src/sst/core/serialization/impl/serialize_insertable.h
When using C-style cast `(value_type&)e` to remove `const` from mapping keys (if any), GCC 14 reports a spurious warning about a user-defined conversion that might be expected to be called, but which isn't called.
> ./../../src/sst/core/serialization/impl/serialize_insertable.h:164:29: **warning: casting ‘std::pair<const int, long unsigned int>’ to ‘SST::Core::Serialization::serialize_impl<std::map<int, long unsigned int, std::less<int>, std::allocator<std::pair<const int, long unsigned int> > >, void>::value_type&’ {aka ‘std::pair<int, long unsigned int>&’} does not use ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_U1, _U2>&)** [with _U1 = const int; _U2 = long unsigned int; typename std::enable_if<(std::_PCC<((! std::is_same<_T1, _U1>::value) || (! std::is_same<_T2, …
> Massage casting to remove warnings on GCC 14

- src/sst/core/serialization/impl/serialize_adapter.h
- src/sst/core/serialization/impl/serialize_insertable.h
- src/sst/core/serialization/impl/serialize_tuple.h
- src/sst/core/serialization/impl/serialize_utility.h
Add new `is_same_type_template_v<>` template and simplify some template type tests
`is_same_type_template_v<TYPE, TEMPLATE>` returns `true` if `TYPE` is a variation of `TEMPLATE` with arguments.
The name is `*_type_template_*` to emphasize that the arguments are a type and a template, respectively, in that order.
Use `is_same_type_template_v<>` to simplify tuple, adapter and insertable container code
Merge pointer and non-pointer `serialize_impl` adapter implementations
Add `is_insertable_v<>` template to test whether a type is an insertable type, and use it to simplify pointer and non-pointer `serialize_impl` implementations for insertable containers
> Merge pointer and non-pointer serialize_impl adapter implementations

- src/sst/core/action.h
- src/sst/core/baseComponent.cc
- src/sst/core/clock.h
- src/sst/core/event.h
- src/sst/core/interfaces/simpleNetwork.h
- src/sst/core/interfaces/stdMem.h
- src/sst/core/oneshot.h
- src/sst/core/serialization/impl/serialize_insertable.h
- src/sst/core/serialization/objectMap.h
- src/sst/core/ssthandler.h
- src/sst/core/testElements/coreTest_Serialization.cc
Two types of compile warnings addressed: unused variables and missing override in functions marked final. 
While the missing override does not warn in all newer versions of gcc, it does warn in older ones that are still supported.
> Fix some warnings found in gcc 8.5-14.2

- src/sst/core/action.h
- src/sst/core/baseComponent.cc
- src/sst/core/clock.h
- src/sst/core/event.h
- src/sst/core/interfaces/simpleNetwork.h
- src/sst/core/interfaces/stdMem.h
- src/sst/core/oneshot.h
- src/sst/core/serialization/impl/serialize_adapter.h
- src/sst/core/serialization/impl/serialize_array.h
- src/sst/core/serialization/impl/serialize_insertable.h
- src/sst/core/serialization/impl/serialize_tuple.h
- src/sst/core/serialization/impl/serialize_utility.h
- src/sst/core/serialization/objectMap.h
- src/sst/core/serialization/serializer.h
- src/sst/core/ssthandler.h
- src/sst/core/testElements/coreTest_Serialization.cc
- tests/testsuite_default_Serialization.py
This adds array serialization tests, and fixes two bugs:
1. `serializer::binary( buffer, size )` did not properly compute `SIZER` with `size * sizeof(ELEM_T)` -- it only used `size` for the `SIZER` computation of the array size. **This should be patched into SST 15 if possible.**
2. If a pointer to a fixed-size array, such as `int (*ary)[10]` was serialized, it was not properly allocated, leading to compilation errors in the template instantiation of `serialize_impl`.
The `serializeDeserialize()` function was modified slightly to take universal references, so that it can work with `array(ptr, size)` wrappers which are rvalue expressions but contain lvalue references inside.
> add array serialization tests, fix bugs

- .github/workflows/PR_clang-format_test.yml
- scripts/clang-format-test.sh
The first part of https://github.com/sstsimulator/sst-core/issues/1236; actual formatting changes will come in a later PR.
(Redo of https://github.com/sstsimulator/sst-core/pull/1317)
> Bump clang-format requirement from v12 to v20

- src/sst/core/eli/defaultInfo.h
- src/sst/core/eli/elementinfo.cc
They are rarely/never used and they prevent tools such as ccache from working correctly due to every compile returning different values.
> core: remove __DATE__ / __TIME__ references from ELI

- configure.ac
- src/sst/core/model/element_python.cc
- src/sst/core/serialization/serializable_base.h
[Reported](https://github.com/tactcomplabs/rev/pull/371) by @kpgriesser 
This continues https://github.com/sstsimulator/sst-core/pull/1254 and adds `-Wmissing-noreturn` to warn about missing `[[noreturn]]` in the future.
> Add -Wmissing-noreturn and [[noreturn]] to more functions

- src/sst/core/threadsafe.h
During a recent SST client build (which was probably misconfigured for other reasons), I found that the `sst_pause()` macro would not be defined if no predefined macros on supported architectures are detected, and so the build fails because `sst_pause()` is undefined and the `src/sst/core/threadsafe.h` header cannot be compiled.
```
/home/lkillough/sstcore-14.1.0/include/sst/core/threadsafe.h: In member function 'double SST::Core::ThreadSafe::Barrier::wait()':
/home/lkillough/sstcore-14.1.0/include/sst/core/threadsafe.h:102:25: error: 'sst_pause' was not declared in this scope
102 |                         sst_pause();
|                         ^~~~~~~~~
/home/lkillough/sstcore-14.1.0/include/sst/core/threadsafe.h: In member function 'void SST::Core::ThreadSafe::Spinlock::lock()': …
```
> Provide std::this_thread::yield() as a default definition of sst_pause()

- src/sst/core/Makefile.am
- src/sst/core/serialization/impl/serialize_bitset.h
- src/sst/core/serialization/serialize.h
- src/sst/core/testElements/coreTest_Serialization.cc
This serializes `std::bitset`, fixing https://github.com/sstsimulator/sst-core/issues/1347 with a solution very specific to `std::bitset` even though it might be able to be handled with trivial serialization in https://github.com/sstsimulator/sst-core/pull/1330.
(Even if https://github.com/sstsimulator/sst-core/pull/1330 is merged, there won't be any conflict, because `serialize_impl<std::bitset<N>>` is "more specialized" and constraining than `serialize_impl<T, std::enable_if_t<...>>` is.)
It leaves open the question of how to implement `std::bitset` mapping mode, and presents issues similar to `std::vector<bool>` with packed bits.
> Serialize std::bitset

- src/sst/core/eli/elementinfo.h
This makes the `InstantiateBuilderInfo<Base, T>::loaded` variable `inline` and moves the `InstantiateBuilderInfo<Base, T>` class definition down so that the `loaded` variable can be initialized inside the class definition.
Although the previous code did not have any ODR-violations (multiple definitions), this was probably because the template arguments were different in each file which `#include`d the header. With C++17 `inline` variables, this makes it safe from ODR violations even if the same template arguments are used in multiple `#include`s of this header file, and makes it simpler to define the variable in-class.
> inline InstantiateBuilderInfo<Base, T>::loaded variable

- src/sst/core/CMakeLists.txt
- src/sst/core/Makefile.am
- src/sst/core/cfgoutput/jsonConfigOutput.cc
- src/sst/core/cfgoutput/pythonConfigOutput.cc
- src/sst/core/config.cc
- src/sst/core/config.h
- src/sst/core/configBase.h
- src/sst/core/main.cc
- src/sst/core/model/python/pymodel.cc
- src/sst/core/timingOutput.cc
- src/sst/core/timingOutput.h
- tests/refFiles/test_TimingInfo.out
- tests/testsuite_default_TimingInfo.py
Added a new command line option `--timing-info-json=FILE` to write timing information into a JSON formatted file. Moved the code to print the timing information to `stdout` from main.cc and into a new file where that data is captured as key-value pairs and then can be printed as text and/or as JSON depending on the command line options. 
Added test case to verify well formed json is generated with the expected keys.
> Generate JSON timing information at end of simulation

- src/sst/core/stringize.h
If an empty string is passed as input, we fall through the loop but still do a push_back on the empty substring.
> core: fix bug in tokenize() function

- .github/scripts/compilers.bash
- .github/scripts/core_autotools_noflags_nodeps.sh
- .github/scripts/core_autotools_noflags_nodeps_nompi.sh
- .github/scripts/elements_autotools_noflags_nodeps.sh
- .github/scripts/elements_autotools_noflags_nodeps_nompi.sh
- .github/scripts/install_os_level_dependencies.sh
- .github/workflows/build_and_test.yml
- .github/workflows/ci.yml
- .github/workflows/free-macos-14.yml
- .github/workflows/free-macos-15.yml
First part of #1053.
There is no AT2 here, just the free runners.  Almost everything needs to be refactored and cleaned up, but this shows how building, testing, and uploading test outputs works.
> GitHub Actions: Initial addition of free macOS runners

- src/sst/core/cfgoutput/pythonConfigOutput.cc
- src/sst/core/cfgoutput/pythonConfigOutput.h
Disambiguates subcomponent object names in Python config output and reorganizes the link construction.  Subcomponent object names in the Python output now contain the subcomponent slot number in order to make them unique.  EG `comp_component30_subcomp_ports0`.  This allows us to reorganize the link instantiation and connectivity logic where all links are created and connected immediate prior to the SST Statistics Python output.  Links are named as their were before, but this PR switches to using the `link.connect((component, port, latency),(component, port, latency))` method.
> Fix for Issue #1391: Disambiguates subcomponent object names in Python config output and reorganizes the link construction

- src/sst/core/Makefile.am
- src/sst/core/cfgoutput/jsonConfigOutput.cc
- src/sst/core/cfgoutput/pythonConfigOutput.cc
- src/sst/core/config.cc
- src/sst/core/config.h
- src/sst/core/factory.cc
- src/sst/core/factory.h
- src/sst/core/main.cc
- src/sst/core/simulation.cc
- src/sst/core/simulation_impl.h
- src/sst/core/sst_mpi.cc
- src/sst/core/sst_mpi.h
- src/sst/core/timingOutput.cc
- src/sst/core/timingOutput.h
- src/sst/core/util/Makefile.inc
- src/sst/core/util/basicPerf.cc
- src/sst/core/util/basicPerf.h
- Better aligned regions for regular and restart runs
- Added comments to regions to better describe what each does
- Added resource tracking at region level
- Changed --print-timing-info to take a verbosity level
- Added some SST version of MPI calls that hide the SST_CONFIF_HAVE_MPI checks
> Reorganize code into regions in main()

- src/sst/core/Makefile.am
- src/sst/core/serialization/impl/serialize_unique_ptr.h
- src/sst/core/serialization/serialize.h
- src/sst/core/testElements/coreTest_Serialization.cc
- tests/testsuite_default_Serialization.py
Serialize `std::unique_ptr`. Wrappers can be used to support unbounded arrays with runtime size, and custom deleters.
> Serialize std::unique_ptr

- src/sst/core/interprocess/mmapparent.cc
This removes some warnings about unused parameters when MPI is disabled. Although the macro is named `UNUSED()`, it turns into `[[maybe_unused]]` which prevents warnings about unused parameters but does not _require_ that they be unused.
```
CXX      sstinfo.o
../../../../src/sst/core/interprocess/mmapparent.cc: In function ‘int SST::Core::Interprocess::SST_MPI_Comm_spawn_multiple(int, char**, char***, const int*, const char**)’:
../../../../src/sst/core/interprocess/mmapparent.cc:27:33: warning: unused parameter ‘count’ [-Wunused-parameter]
27 | SST_MPI_Comm_spawn_multiple(int count, char* array_of_commands[], char** array_of_argv[], const int array_of_maxprocs[],
|                             ~~~~^~~~~
../../../../src/sst/core/interprocess/mmapparent.cc:27:46: warning: unused parameter …
```
> Remove warnings when MPI is disabled

- src/sst/core/interprocess/mmapparent.cc
- src/sst/core/serialization/impl/serialize_insertable.h
This is a mostly-cosmetic change to the container serialization code.
Previously, a `//clang-format on` comment instead of the correct `// clang-format on` caused the rest of the file to not be bound by `clang-format` rules.
> Cleanup container serialization code
