sstsimulator/sst-core

from_string.h, params.h
Added new code for templated find functions in Params. Removed some of the old map-like functions from Params; will remove the rest once none of the elements reference them.
=> Param cleanup

Makefile.am, src/sst/core/Makefile.am
Erase this information and put your Pull Request comments here <BR><BR><BR>
---
`1` Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-core
`2` Verify that Source branch is up to date with the devel branch of sst-core
`3` After submitting your Pull Request:
* Automatic Testing will commence in a short while 
* Pull Requests will be tested with the devel branches of the sst-elements and sst-sqe repositories
* These branches are syncronized with the devel branch of sst-core.  This is why is it important to keep your source branch up to date.
* If testing passes, the SST Core developers will review your changes and merge them or contact you for more information
* If testing fails, You will be notified of the test results.  
* The Pull Request will be …
=> Small fixes for the Make Dist test

src/sst/core/config.h, src/sst/core/elemLoader.cc
Adds Verbose Print out for Library Path Resolution
=> Adds Verbose Print out for Library Path Resolution

src/sst/core/elemLoader.cc
=> Commented out warning about not being able to find a library.

src/sst/core/subcomponent.cc, src/sst/core/subcomponent.h
---
`1` Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-core
`2` Verify that Source branch is up to date with the devel branch of sst-core
`3` After submitting your Pull Request:
* Automatic Testing will commence in a short while 
* Pull Requests will be tested with the devel branches of the sst-elements and sst-sqe repositories
* These branches are syncronized with the devel branch of sst-core.  This is why is it important to keep your source branch up to date.
* If testing passes, the SST Core developers will review your changes and merge them or contact you for more information
* If testing fails, You will be notified of the test results.  
* The Pull Request will be retested on a regular basis - Changes to the source branch can be made to correct …
=> Added isPortConnected to SubComponent.

config/sst_check_boost.m4
Attempt to fix up configure for OSX systems.  Boost checks attempt link-based checking (rather than just compile checking), and attempts the -mt variant as well as standard library.
=> [configure] Do link tests for Boost libraries.  Attempt -mt variants

src/sst/core/mainpage.dox
Doxygen generation was missing the main page.  This is a first cut of one.
=> Adding main page for Doxygen generation

src/sst/core/sharedRegion.cc
Addressing #38 .   Detects overlaps in changeSets during merge, and fails if it finds overlapping ranges.
=> [SharedRegionMerger] Detects for range overlaps

Makefile.am, src/sst/core/Makefile.am
Added extra dist files for the various support files (Caps Files), and the doxygen mainpage file.
=> Added extra-dist for various support files

src/sst/core/boostExports.cc, src/sst/core/config.h, src/sst/core/configGraph.h, src/sst/core/objectComms.h, src/sst/core/params.h, src/sst/core/rankInfo.h, src/sst/core/serialization/serializable.cc, src/sst/core/serialization/serializable.h, src/sst/core/serialization/serialize_array.h, src/sst/core/serialization/serializer.h, src/sst/core/sharedRegion.cc, src/sst/core/sharedRegionImpl.h, src/sst/core/sparseVectorMap.h
Move to having all core data structures use new serialization in preparation for removing dependence on boost serialization.
=> Serialization

src/sst/core/config.h, src/sst/core/model/pymodel.cc
=> Support sst.setThreadCount() in python

src/sst/core/Makefile.am, src/sst/core/interprocess/circularBuffer.h, src/sst/core/interprocess/ipctunnel.cc, src/sst/core/interprocess/ipctunnel.h
This branch is dependent upon the sst-elements / bjmoor/interprocess branch.
Manual testing was performed multiple times on Ubuntu, sst-test, and MacOSX platforms suing the bjmoor/interproces brances of sst-core and sst-elements along with the devel branch of sst-sqe.  All tests have passed.
The Pull request will be manually merged to avoid synchronization issues with the autotester.
=> Merge Bjmoor/interprocess branch to sst-core

src/sst/core/interprocess/ipctunnel.h
=> Auto-unlink after all children have attached

src/sst/core/model/pymodel.cc, src/sst/core/model/pymodel.h
Feature addition:   Python 'sst.findComponentByName()'.  Addresses #123
=> Add support for looking up components by name

src/sst/core/interprocess/ipctunnel.h
When IPC startup file clashes, retry with a different filename.
=> Retry on EEXIST errors in IPC setup

config/sst_check_zoltan.m4
Fixes Zoltan Configure Issue where ./configure wouldn't fail if not found.
=> Fixes Zoltan Configure Issue where ./configure wouldn't fail if not found.

configure.ac
=> Change email address to sst@sandia.gov for configure

src/sst/core/elemLoader.cc
Erase this information and put your Pull Request comments here <BR><BR><BR>
---
`1` Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-core
`2` Verify that Source branch is up to date with the devel branch of sst-core
`3` After submitting your Pull Request:
* Automatic Testing will commence in a short while 
* Pull Requests will be tested with the devel branches of the sst-elements and sst-sqe repositories
* These branches are syncronized with the devel branch of sst-core.  This is why is it important to keep your source branch up to date.
* If testing passes, the SST Core developers will review your changes and merge them or contact you for more information
* If testing fails, You will be notified of the test results.  
* The Pull Request will be …
=> fix misuse of r-value reference return: Issue #136

src/sst/core/serialization/serialize_array.h
=> Serialize array fix for issue #135.

src/sst/core/elemLoader.cc, src/sst/core/serialization/serialize_array.h
Sync `master` and `devel` branch.
=> Ensure Master is up to date with Devel

config/sst_check_hdf5.m4, configure.ac, src/sst/core/Makefile.am, src/sst/core/factory.cc, src/sst/core/statapi/componentregisterstat_impl.h, src/sst/core/statapi/statoutput.cc, src/sst/core/statapi/statoutput.h, src/sst/core/statapi/statoutputhdf5.cc, src/sst/core/statapi/statoutputhdf5.h
Initial support for an HDF5-based Stat Output module.
=> [core] Add new StatOutputHDF5

src/sst/core/config.cc, src/sst/core/config.h, src/sst/core/main.cc, src/sst/core/simulation.cc
Implement a --stopAfter flag.   See Issue #27 .  Can specify an amount of time, after which, SST will force shutdown.
=> Implement a --stopAfter flag

src/sst/core/cfgoutput/pythonConfigOutput.cc
This fix handles cases where components have had the shortcut "enable all" statistics set, for the `--output-config`.   See Issue #26
=> Fix stat enablement for ENABLE ALL statistics

src/sst/core/elemLoader.cc, src/sst/core/elemLoader.h, src/sst/core/sstinfo.cc, src/sst/core/sstinfo.h
Also address part of #17   (adds partitioners, adds SST Core ELI (though not fully flushed out at this point)
=> [sstinfo] Simplify library searches.  Include SST Core info

src/sst/core/threadSyncSimpleSkip.cc, src/sst/core/threadSyncSimpleSkip.h, src/sst/core/threadsafe.h
* Break apart more barrier re-use.
* Add spin back-off to barrier during wait
* Add memory fence to barrier release.
=> Barrier tweaks

src/sst/core/configGraph.cc
=> Make it an error to use an invalid port name.

config/sst_check_hdf5.m4, configure.ac
=> Modify HDF5 checking to check ABI compatibility

config/sst_check_boost.m4, configure.ac
Make's Boost an optional dependency of the SST Core.
=> Make Boost Optional for the SST Core

config/sst_check_libz.m4, configure.ac
Additional support for libz detect/configure. Will help to address issue #25.
=> Additional Support for libz detect/configure

src/sst/core/baseComponent.cc, src/sst/core/baseComponent.h, src/sst/core/cfgoutput/pythonConfigOutput.cc, src/sst/core/componentInfo.cc, src/sst/core/componentInfo.h, src/sst/core/configGraph.cc, src/sst/core/configGraph.h, src/sst/core/element.h, src/sst/core/elementinfo.h, src/sst/core/elibase.h, src/sst/core/model/pymodel_comp.cc, src/sst/core/model/pymodel_comp.h, src/sst/core/simulation.cc, src/sst/core/subcomponent.h
This is the initial support for "Multi-slot" Subcomponents. All SubComponentSlots now support having multiple SubComponents loaded. This does not yet include support for this in the new ELI and doesn't use the ELI documentation to do checking. That will come in a future pull request.
=> Eli change - Making SubComponentSlots support multiple SubComponents.

src/sst/core/sstinfo.cc, src/sst/core/sstinfo.h
=> Update sst-info for new ELI structure

src/sst/core/serialization/serialize_packer.h, src/sst/core/serialization/serialize_unpacker.h, src/sst/core/serialization/serializer.cc, src/sst/core/serialization/serializer.h
Suggested fix. Doesn't have to be done that way.
=> bug fix for serializing null buffers: Issue #240

LICENSE
Update LICENSE information to reflect the change in Sandia's management.
=> Updated to NTESS contract number and funding statement

src/sst/core/Makefile.am, src/sst/core/factory.cc, src/sst/core/statapi/statoutputjson.cc, src/sst/core/statapi/statoutputjson.h
Initial statistics output generator to JSON format. Requested by @bjmoor in #273.
=> Add Statistics Output for in JSON Format

src/sst/core/mempool.h, src/sst/core/threadsafe.h
Modify assembly and hardware yields to compile on PPC64-LE.
=> Modify Assembly and Hardware Yields to compile on PPC64-LE

src/sst/core/env/envquery.cc
Fix some compile warnings with GCC 4.8.5 on POWER8
=> Fix some compile warnings with GCC 4.8.5 on POWER8

src/sst/core/sstinfo.cc
=> [sstinfo] enable XML output of subcomponent information

src/sst/core/sstinfo.cc, src/sst/core/sstinfo.h
Emit the interface information for subcomponents and subcomponent slots.
=> [sstinfo] Output subcomponent interface information

src/sst/core/decimal_fixedpoint.h, src/sst/core/threadsafe.h
Addresses undefined behavior, and fix missing fence in Spinlock
=> Fixes for Power8

src/sst/core/simulation.cc, src/sst/core/simulation.h
Added barriers between calling finish, emergencyShutdown and statistics end of simulation.
=> Fix timing of simulation end functions

src/sst/core/statapi/stataccumulator.h
=> Add Min and Max outputs for Accumulator statistics

src/sst/core/model/element_python.cc, src/sst/core/model/element_python.h
Added a new class for creating a hierarchy of modules for element library python modules.
Added error checking and reporting into the module loading so that loads don't fail without useful information.
=> Added support for hierarchal python module definitions

src/sst/core/cfgoutput/pythonConfigOutput.cc, src/sst/core/model/pymodel_comp.cc, src/sst/core/model/pymodel_link.cc
Also fixed a few debug messages.
=> Fixed PythonConfigGraphOutput to output latencies in the correct timebase

src/sst/core/sstregistertool.cc
Updated sstregister tool to allow for unregistering models manually and automatically
=> sstregistertool

config/sst_check_preview_build.m4, src/sst/core/baseComponent.cc, src/sst/core/baseComponent.h, src/sst/sst.conf
Changed. name of conditioned fatal() to set_assert in BaseComponent.
Added PREVIEW_BUILD field to sstsimulator.conf.
=> Added PREVIEW_BUILD field to sstsimulator.conf.

src/sst/core/link.cc, src/sst/core/link.h
Make setLatency() private (bug)
Add new addSendLatency() functions (enhancement)
=> Fixes for issue #477

src/sst/core/interprocess/circularBuffer.h, src/sst/core/interprocess/ipctunnel.h, src/sst/core/interprocess/mmapparent.h, src/sst/core/interprocess/shmchild.h, src/sst/core/interprocess/shmparent.h, src/sst/core/interprocess/tunneldef.h
This fixes the build failures on Mac/Sierra.
=> Add missing includes

src/sst/core/baseComponent.cc, src/sst/core/componentInfo.h, src/sst/core/statapi/stataccumulator.h, src/sst/core/statapi/statbase.cc, src/sst/core/statapi/statbase.h, src/sst/core/statapi/statengine.cc, src/sst/core/statapi/statengine.h, src/sst/core/statapi/stathistogram.h, src/sst/core/statapi/statnull.h, src/sst/core/statapi/statoutput.cc, src/sst/core/statapi/statoutput.h, src/sst/core/statapi/statoutputconsole.cc, src/sst/core/statapi/statoutputconsole.h, src/sst/core/statapi/statoutputcsv.cc, src/sst/core/statapi/statoutputcsv.h, src/sst/core/statapi/statoutputhdf5.cc, src/sst/core/statapi/statoutputhdf5.h, src/sst/core/statapi/statoutputjson.cc, src/sst/core/statapi/statoutputjson.h, src/sst/core/statapi/statoutputtxt.cc, src/sst/core/statapi/statoutputtxt.h, src/sst/core/statapi/statuniquecount.h
Backwards compatible, but creates the possibility of a statistic output that does not register fields.
=> Stats generalizations: #398 #400 #401

src/sst/core/baseComponent.cc, src/sst/core/componentInfo.cc, src/sst/core/componentInfo.h, src/sst/core/configGraph.cc, src/sst/core/configGraph.h, src/sst/core/model/element_python.cc, src/sst/core/model/python2/pymodel.cc, src/sst/core/model/python2/pymodel.h, src/sst/core/model/python2/pymodel_comp.cc, src/sst/core/model/python2/pymodel_comp.h, src/sst/core/model/python3/pymodel.cc, src/sst/core/model/python3/pymodel.h, src/sst/core/model/python3/pymodel_comp.cc, src/sst/core/model/python3/pymodel_comp.h, src/sst/core/statapi/statengine.cc, src/sst/core/statapi/statengine.h, src/sst/core/statapi/statoutput.h
Updates the python stat enable API to work with both SubComponents and Components.  Also added the ability to apply changes to children.
=> Subcomp stat python

src/sst/core/configGraph.cc, src/sst/core/configGraph.h, src/sst/core/model/python2/pymodel_comp.cc, src/sst/core/model/python3/pymodel_comp.cc
Fixed getFullName() call and added getType() on component/subcomponent python objects.
=> Python updates 

src/sst/core/baseComponent.cc, src/sst/core/baseComponent.h, src/sst/core/oneshot.cc, src/sst/core/oneshot.h
Fixed oneshot implmentation so that registering oneshots of the same latency don't overwrite each other.  Also fixed a while lloop in stats handling in BaseComponent.
=> Core OneShot fix

src/sst/core/model/python/pymacros.h
* Fixes build issues with Python <= 3.7
=> Unify python

src/sst/core/configGraph.cc, src/sst/core/configGraph.h, src/sst/core/params.cc, src/sst/core/serialization/serialize_map.h, src/sst/core/serialization/serialize_set.h, src/sst/core/sparseVectorMap.h
Enhancements to reduce the complexity of algorithms used to create PartitionGraphs and to check Links when connecting.  Also added serialization for unordered_map and unordered_set.
=> Startup performance enhancements

src/sst/core/testingframework/readme.md, src/sst/core/testingframework/sst_unittest_support.py, src/sst/core/testingframework/test_engine.py, src/sst/core/testingframework/test_engine_unittest.py, tests/testsuite_default_sstinfo.py
Functionality Improvements to Test Frameworks
- Tweaks to PIN detection functions.
- Added support for -e parameter to allow running a specific test in the discovered test suites and associated documentation.
- Added breakdown of total test time in hours, minutes and seconds.
=> Newtestframeworks changes

src/sst/core/baseComponent.h, src/sst/core/componentInfo.h, src/sst/core/link.h, src/sst/core/params.cc, src/sst/core/params.h
Added Link::replaceFunctor() that will delete current functor and replace with new one.
Added BaseComponent::getParentComponentName().
Changed Param::count and Param::contains to be const.
=> Small tweaks to some core APIs.

src/sst/core/Makefile.am, src/sst/core/baseComponent.cc, src/sst/core/config.cc, src/sst/core/config.h, src/sst/core/main.cc, src/sst/core/serialization/serializable.h, src/sst/core/shared/Makefile.inc, src/sst/core/shared/sharedArray.h, src/sst/core/shared/sharedMap.h, src/sst/core/shared/sharedObject.cc, src/sst/core/shared/sharedObject.h, src/sst/core/shared/sharedSet.h, src/sst/core/sharedRegion.cc, src/sst/core/sharedRegion.h, src/sst/core/sharedRegionImpl.h, src/sst/core/simulation.cc, src/sst/core/testElements/Makefile.inc, src/sst/core/testElements/coreTest_LookupTableComponent.cc, src/sst/core/testElements/coreTest_SharedObjectComponent.cc, src/sst/core/testElements/coreTest_SharedObjectComponent.h, src/sst/core/testingframework/sst_unittest.py, tests/Makefile.inc, tests/refFiles/test_UnitAlgebra.out, tests/test_SharedObject.py, tests/testsuite_default_SharedObject.py, tests/testsuite_default_UnitAlgebra.py
Added the ability to use SharedRegions when not all instances know the size of the region.
Added SharedArray and SharedMap as new ways to share readonly data.
=> Shared region enhancements

src/sst/core/cfgoutput/dotConfigOutput.cc, src/sst/core/cfgoutput/dotConfigOutput.h, src/sst/core/config.cc, src/sst/core/config.h
Modifying dot output to have a verbosity flag allowing for different levels of detail in the output graph
=> Dot Config Output Verbosity

src/sst/core/config.cc, src/sst/core/testElements/Makefile.inc, src/sst/core/testElements/coreTest_ClockerComponent.cc, src/sst/core/testElements/coreTest_SharedObjectComponent.cc
Cleaning up some build warnings
=> Cleanup some build warnings

src/sst/core/baseComponent.h, src/sst/core/clock.h, src/sst/core/impl/partitioners/linpart.h, src/sst/core/impl/partitioners/rrobin.h, src/sst/core/impl/partitioners/selfpart.h, src/sst/core/impl/partitioners/simplepart.h, src/sst/core/impl/partitioners/singlepart.h, src/sst/core/impl/partitioners/zoltpart.h, src/sst/core/interfaces/stdMem.h, src/sst/core/link.cc, src/sst/core/link.h, src/sst/core/timeConverter.h, src/sst/core/timeLord.cc
Cleaned up some inherited functions in partitioners and dif some other general cleanup for release.
=> Final cleanup for 11 release

src/sst/core/statapi/statoutputjson.cc
Fix JSON formatting bug in #634
=> Fix JSON Bug in #634

src/sst/core/component.h, src/sst/core/eli/elementinfo.h, src/sst/core/eli/elibase.h, src/sst/core/eli/paramsInfo.h, src/sst/core/eli/portsInfo.h, src/sst/core/eli/statsInfo.h, src/sst/core/eli/subcompSlotInfo.h, src/sst/core/testElements/coreTest_Component.cc, src/sst/core/testElements/coreTest_Component.h, src/sst/core/testElements/coreTest_SubComponent.cc, src/sst/core/testElements/coreTest_SubComponent.h
Also removed class ElementInfoPort2 because it was only there for backward compatibility with the old ELI format.
=> Added inheritance for ELI information.

src/sst/core/objectComms.h
Attempt to address #664 I did not exhaustively prove that the serializer doesn't clean up these pointers, hopefully our tests would fail with the double free if that is the case.
=> Communication leaks

.gitignore, Makefile.am, scripts/clang-format-test.sh
Attempted fix for #671 just FYI running the script generates failures on on current devel.
=> Added a #!/bin/bash to the top of the clang format script.

.clang-format, src/sst/core/action.h, src/sst/core/activity.h, src/sst/core/clock.h, src/sst/core/event.h, src/sst/core/serialization/serializable.h, src/sst/core/simulation.cc, src/sst/core/simulation.h, src/sst/core/simulation_impl.h, src/sst/core/timeConverter.h
A couple bug fixes plus some extra util functions for better debug prints and getting timing information.
=> Util functions

scripts/clang-format-test.sh
I wanted a way to change the exe for the clang-format script. Also I want it to complain if the user has the wrong version of clang-format.
=> Added checking to the format script to ensure the version is correct

.github/workflows/PR_clang-format_test.yml
Update GHA script to perform clang-format test with ability to add/modify labels and submit comments into the conversation.
=> Update GHA script

src/sst/core/Makefile.am, src/sst/core/clock.h, src/sst/core/event.h, src/sst/core/interfaces/simpleMem.h, src/sst/core/interfaces/simpleNetwork.h, src/sst/core/interfaces/stdMem.h, src/sst/core/oneshot.h, src/sst/core/ssthandler.h, src/sst/core/testElements/coreTest_SubComponent.h
Created a new core-wide handler base class
=> Handler update

src/sst/core/interfaces/stdMem.cc, src/sst/core/interfaces/stdMem.h, src/sst/core/testingframework/sst_unittest.py, src/sst/core/testingframework/test_engine_support.py
Step 1 of moving StandardMem out of experimental namespace
Also a couple minor test frameworks fixes
=> Move StandardMem out of experimental

src/sst/core/baseComponent.h, src/sst/core/cfgoutput/dotConfigOutput.cc, src/sst/core/cfgoutput/jsonConfigOutput.cc, src/sst/core/cfgoutput/pythonConfigOutput.cc, src/sst/core/component.h, src/sst/core/config.cc, src/sst/core/config.h, src/sst/core/configGraph.h, src/sst/core/configGraphOutput.h, src/sst/core/main.cc, src/sst/core/model/json/jsonmodel.cc, src/sst/core/model/python/pymodel.cc, src/sst/core/model/python/pymodel.h, src/sst/core/model/sstmodel.cc, src/sst/core/model/sstmodel.h, src/sst/core/params.cc, src/sst/core/params.h, src/sst/core/simulation.cc
Cleaned up Config and Params APIs to clarify the element public versus core private APIs.  Also cleaned up the usage message.  Also deprecated the Component and BaseComponent default constructors since they are no longer needed and should not be used.
=> Config and Param clean up

src/sst/core/config.cc, src/sst/core/config.h, src/sst/core/main.cc, src/sst/core/params.cc, src/sst/core/testElements/coreTest_ParamComponent.cc, tests/refFiles/test_ParamComponent.out, tests/test_ParamComponent.py
Fixed bug in global params for case when a global set was set for a component before it was initialized with any data.  Also added new --force-rank-seq-startup flag for debug purposes.
=> Global param ordering fix

src/sst/core/elemLoader.cc
The loader will now gather all loading errors from dlopen for existing files.  These will be printed as an error if the library doesn't load and as a warning if it does find a valid library to load.
=> Improved the error message printed when a library fails to load.

src/sst/core/Makefile.am, src/sst/core/configGraph.cc, src/sst/core/elemLoader.cc, src/sst/core/namecheck.cc, src/sst/core/namecheck.h, src/sst/core/sst_types.h, src/sst/core/testElements/coreTest_ParamComponent.cc, src/sst/core/testElements/coreTest_ParamComponent.h, tests/refFiles/test_ParamComponent.out, tests/test_ParamComponent.py
Also created a central place for the name check code in namecheck.{h,cc}.
=> Added param, port and slot name checking.

src/sst/core/baseComponent.cc, src/sst/core/baseComponent.h, src/sst/core/configGraph.cc, src/sst/core/event.cc, src/sst/core/exit.cc, src/sst/core/factory.cc, src/sst/core/link.cc, src/sst/core/model/element_python.cc, src/sst/core/oneshot.cc, src/sst/core/shared/sharedArray.h, src/sst/core/shared/sharedMap.h, src/sst/core/shared/sharedObject.cc, src/sst/core/shared/sharedObject.h, src/sst/core/shared/sharedSet.h, src/sst/core/simulation.cc, src/sst/core/simulation.h, src/sst/core/simulation_impl.h, src/sst/core/statapi/statfieldinfo.cc, src/sst/core/statapi/statoutput.cc, src/sst/core/statapi/statoutputcsv.cc, src/sst/core/statapi/statoutputjson.cc, src/sst/core/statapi/statoutputtxt.cc, src/sst/core/testElements/coreTest_Component.cc, src/sst/core/testElements/coreTest_Links.cc, src/sst/core/testElements/coreTest_ParamComponent.cc, src/sst/core/testElements/coreTest_PerfComponent.cc, src/sst/core/testElements/coreTest_StatisticsComponent.cc
Added all APIs that weren't already in BaseComponent to the BaseComponent API.
=> Deprecated Simulation::getSimulation() 

src/sst/core/baseComponent.cc, src/sst/core/baseComponent.h, src/sst/core/event.h, src/sst/core/exit.cc, src/sst/core/exit.h, src/sst/core/simulation.cc, src/sst/core/timeLord.cc
Fixes so that core timebases larger than 1ns will work.
=> Large core timebase

src/sst/core/baseComponent.cc, src/sst/core/baseComponent.h
Performance fix for getCurrentSimTimeNano/Micro/Milli.
=> Time query fix

src/sst/core/model/json/jsonmodel.cc, src/sst/core/model/python/pymodel.cc, src/sst/core/statapi/statoutputhdf5.cc, src/sst/core/testElements/coreTest_Component.cc, src/sst/core/testElements/coreTest_PerfComponent.cc, src/sst/core/testingframework/sst_unittest_support.py, tests/testsuite_default_Links.py
A few minor bug and testing fixes.
=> Minor bug fixes

.gitignore, doc/.gitignore, src/sst/core/configGraph.cc, src/sst/core/event.h, src/sst/core/link.cc, src/sst/core/rng/uniform.h, src/sst/core/serialization/serialize_buffer_accessor.h, src/sst/core/simulation.cc
Closes #736
These are all the patches from https://github.com/sstsimulator/sst-core/issues/736#issuecomment-1125512738 except for the case fallthrough, where the original code no longer exists.
=> Minor tidying

configure.ac
Fixes https://github.com/sstsimulator/sst-elements/issues/1558
=> Allow generic debug flags

src/sst/core/sstregistertool.cc
Closes #991 
Redo of #992 for correct branch
=> Switch from tmpnam to mkstemp

src/sst/core/unitAlgebra.h
=> Doxygen for UnitAlgebra exceptions

Makefile.am, scripts/sst-snippets.py
Added sst-snippets.py script which creates source code snippets useful for documentation.
=> Added source code snippeting script.

.github/workflows/ci.yml, .github/workflows/pre-commit.yml, .pre-commit-config.yaml
=> GitHub Actions infrastructure for formatting checks

src/sst/core/model/python/pymacros.h, src/sst/core/model/python/pymodel.cc, src/sst/core/model/python/pymodel_comp.cc, src/sst/core/model/python/pymodel_link.cc, src/sst/core/model/python/pymodel_stat.cc, src/sst/core/model/python/pymodel_statgroup.cc, src/sst/core/model/python/pymodel_unitalgebra.cc
=> Python fix

config/ax_compiler_vendor.m4, configure.ac
Closes https://github.com/sstsimulator/sst-core/issues/1015
=> Disable fused floating-point operations with Clang

src/sst/core/sstinfo.cc
=> add missing algorithm include to sstinfo

src/sst/core/statapi/statbase.cc, src/sst/core/statapi/statengine.cc, src/sst/core/statapi/statfieldinfo.cc, src/sst/core/statapi/statfieldinfo.h, tests/test_RNGComponent.py
stat field lookup update
RNG test python syntax fix
=> Change to lookup stat field ID on restart

src/sst/core/testingframework/sst_unittest.py, tests/testsuite_default_sstinfo.py
Update sstinfo tests to use OSCommand timeout, add check for curses
=> Fix SST-Info Tests

src/sst/core/baseComponent.cc, src/sst/core/interfaces/stdMem.h
Also fix typo in allowed statistics parameters
=> Add CacheFlush instruction to StandardMem interface

src/sst/core/statapi/statoutputhdf5.cc, tests/refFiles/test_StatisticsComponent_basic_h5.out
Fixes compile issue in HDF5 stat output object.
Updates HDF5 ref file for recently changed test.
=> Fixes for HDF5 stat output and test

src/sst/core/config.cc, src/sst/core/realtime.cc, src/sst/core/realtime.h, src/sst/core/realtimeAction.h, src/sst/core/serialization/objectMap.h, src/sst/core/simulation.cc
This PR add supports for a realtime action (sst.rt.interactive) to break to an interactive console from sigusr1 or sigusr2. It causes an error if used with sigalrm. Issue #1225 
---
Instructions for Issuing a Pull Request to sst-core
---------------------------------------------------
1 - Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-core
2 - Verify that Source branch is up to date with the devel branch of sst-core
3 - After submitting your Pull Request:
* Automatic Testing will commence in a short while 
* Pull Requests will be tested with the devel branches of the sst-elements and sst-sqe repositories
* These branches are syncronized with the devel branch of sst-core.  This is why is it important to keep your source branch up to date.
* If testing …
=> Interactive console realtime action

src/sst/core/serialization/impl/serialize_insertable.h
This changes the serialization code to expect a `.clear()` method for the container and to call it during unpacking instead of destroying and re-constructing a new container, so that reserved sizes of vectors and `std::unordered_*` buckets is preserved during unpacking. When it unpacks a vector, it calls `.reserve()` on the size before inserting elements.
It also defines `is_simple_map` and `is_simple_set` traits for non-multimaps/multisets which contain arithmetic and `enum` keys, as well as any key which is convertible to `std::string` (such as if `operator std::string()` is defined for a class). The key converted to a string is used in the object map. Right now this hasn't been done for sets yet, because I'm not sure how to convert sets into map pairs (right now an integer index …
=> Use .clear() and .reserve() when unpacking containers; handle maps with simple keys which can be converted to string

src/sst/core/activity.h, src/sst/core/baseComponent.cc, src/sst/core/baseComponent.h, src/sst/core/componentInfo.cc, src/sst/core/componentInfo.h, src/sst/core/interfaces/stdMem.h, src/sst/core/link.cc, src/sst/core/link.h, src/sst/core/main.cc, src/sst/core/simulation.cc, src/sst/core/simulation_impl.h, src/sst/core/sync/rankSyncParallelSkip.cc, src/sst/core/sync/rankSyncSerialSkip.cc, src/sst/core/sync/syncManager.cc, src/sst/core/sync/syncManager.h, src/sst/core/timeConverter.h, src/sst/core/timeLord.cc, src/sst/core/timeLord.h, src/sst/core/warnmacros.h
Moved more of core to use TimeConverter instead of TimeConverter*
=> Tc updates

src/sst/core/timeConverter.h
Fix nullptr_t -> std::nullptr_t and add deprecation message to TimeConverter(std::nullptr_t)
=> TimeConverter fix

src/sst/core/config.cc, src/sst/core/serialization/impl/serialize_array.h
Fix ordering issue in call to sst_ser_obj and fix documentation on checkpoint-prefix.
=> Serialize array bug

src/sst/core/baseComponent.cc, src/sst/core/util/filesystem.h
Fix missing function implementation
Also fix some typos in filesystem
=> Bug fix for timeconverter/basecomponent API

src/sst/core/Makefile.am, src/sst/core/serialization/impl/serialize_optional.h, src/sst/core/serialization/serialize.h, src/sst/core/testElements/coreTest_Serialization.cc, tests/testsuite_default_Serialization.py
This adds serialization of `std::optional`
=> Serialize std::optional

src/sst/core/componentExtension.h, src/sst/core/config.cc, src/sst/core/config.h, src/sst/core/configBase.cc, src/sst/core/configBase.h, src/sst/core/configShared.cc, src/sst/core/configShared.h, src/sst/core/main.cc, src/sst/core/params.cc, src/sst/core/simulation.cc, src/sst/core/simulation_impl.h, src/sst/core/sstinfo.cc
Checkpoint Config object and merge with new Config on restart.  Merge some regular and restart paths based on having the merged Config early on in the execution.
=> Checkpoint config object
